import json
import os

os.chdir(r"c:\Users\unnat\OneDrive\Desktop\Documents\Desktop\Vyavastha\frontend\src\i18n\translations")

# Complete translations for all 30 languages with proper native text
all_translations = {
    "ar": {
        "common": {
            "submit": "إرسال",
            "cancel": "إلغاء الأمر",
            "loading": "جاري التحميل...",
            "error": "خطأ",
            "success": "نجح!",
            "warning": "تحذير",
            "info": "معلومة",
            "back": "رجوع",
            "next": "التالي",
            "done": "تم",
            "close": "إغلاق",
            "save": "حفظ",
            "delete": "حذف",
            "edit": "تعديل",
            "logout": "تسجيل الخروج",
            "language": "اللغة",
            "settings": "الإعدادات",
            "help": "مساعدة",
            "about": "حول"
        },
        "category": {
            "title": "اختر الفئة",
            "water": "المياه",
            "electricity": "الكهرباء",
            "road": "الطرق",
            "garbage": "النفايات",
            "sewer": "الصرف الصحي",
            "streetlight": "أنوار الشارع",
            "park": "الحديقة العامة",
            "other": "أخرى",
            "description": "الوصف",
            "selectCategory": "اختر فئة الشكوى",
            "categoryRequired": "الفئة مطلوبة",
            "categoryError": "خطأ في الفئة"
        },
        "complaint": {
            "title": "تقديم شكوى",
            "description": "الوصف",
            "location": "الموقع",
            "submit": "إرسال",
            "cancel": "إلغاء",
            "uploadImage": "رفع صورة",
            "status": "الحالة",
            "pending": "قيد الانتظار",
            "resolved": "تم حلها",
            "rejected": "مرفوضة",
            "inProgress": "قيد المعالجة",
            "assignTo": "عين ل",
            "category": "الفئة",
            "urgency": "الاستعجالية",
            "high": "عالية",
            "medium": "متوسطة",
            "low": "منخفضة",
            "attachments": "المرفقات"
        },
        "roles": {
            "title": "اختر دورك",
            "citizen": "مواطن",
            "official": "موظف حكومي",
            "admin": "مسؤول",
            "citizenDesc": "إبلاغ عن المشاكل والشكاوى",
            "officialDesc": "معالجة الشكاوى والمشاكل",
            "adminDesc": "إدارة النظام والمستخدمين",
            "selectRole": "اختر دورك",
            "continue": "استمرار"
        },
        "bottomNav": {
            "home": "الرئيسية",
            "complaints": "الشكاوى",
            "profile": "الملف الشخصي",
            "notifications": "الإشعارات"
        },
        "splash": {
            "title": "فياوستا",
            "subtitle": "نظام إدارة الشكاوى"
        },
        "home": {
            "welcome": "مرحبا",
            "recentComplaints": "الشكاوى الأخيرة",
            "noComplaints": "لا توجد شكاوى",
            "fileComplaint": "تقديم شكوى جديدة",
            "stats": "الإحصائيات",
            "resolved": "تم حلها",
            "pending": "قيد الانتظار",
            "total": "الإجمالي",
            "viewAll": "عرض الكل"
        },
        "auth": {
            "login": "تسجيل الدخول",
            "signup": "إنشاء حساب",
            "email": "البريد الإلكتروني",
            "password": "كلمة المرور",
            "phone": "رقم الهاتف",
            "name": "الاسم",
            "forgotPassword": "هل نسيت كلمة مرورك؟",
            "rememberMe": "تذكرني",
            "noAccount": "ليس لديك حساب؟",
            "haveAccount": "هل لديك حساب؟",
            "enterOTP": "أدخل رمز OTP",
            "sendOTP": "إرسال OTP",
            "verifyOTP": "التحقق من OTP",
            "invalidEmail": "بريد إلكتروني غير صحيح",
            "invalidPhone": "رقم هاتف غير صحيح",
            "passwordMismatch": "كلمات المرور غير متطابقة",
            "loginSuccess": "تم تسجيل الدخول بنجاح",
            "signupSuccess": "تم إنشاء الحساب بنجاح",
            "loginError": "خطأ في تسجيل الدخول",
            "signupError": "خطأ في إنشاء الحساب"
        },
        "profile": {
            "title": "الملف الشخصي",
            "name": "الاسم",
            "email": "البريد الإلكتروني",
            "phone": "رقم الهاتف",
            "address": "العنوان",
            "edit": "تعديل",
            "logout": "تسجيل الخروج"
        },
        "notifications": {
            "title": "الإشعارات",
            "noNotifications": "لا توجد إشعارات",
            "markAsRead": "وضع علامة كمقروء"
        },
        "complaints": {
            "title": "الشكاوى",
            "filter": "تصفية",
            "sort": "ترتيب",
            "status": "الحالة"
        },
        "languages": {
            "ar": "العربية",
            "bn": "البنغالية",
            "cs": "التشيكية",
            "de": "الألمانية",
            "el": "اليونانية",
            "en": "الإنجليزية",
            "es": "الإسبانية",
            "fil": "الفيليبينية",
            "fr": "الفرنسية",
            "gu": "الجوجاراتية",
            "he": "العبرية",
            "hi": "الهندية",
            "id": "الإندونيسية"
        }
    },
    "cs": {
        "common": {
            "submit": "Odeslat",
            "cancel": "Zrušit",
            "loading": "Načítání...",
            "error": "Chyba",
            "success": "Úspěch!",
            "warning": "Upozornění",
            "info": "Informace",
            "back": "Zpět",
            "next": "Další",
            "done": "Hotovo",
            "close": "Zavřít",
            "save": "Uložit",
            "delete": "Smazat",
            "edit": "Upravit",
            "logout": "Odhlásit se",
            "language": "Jazyk",
            "settings": "Nastavení",
            "help": "Pomoc",
            "about": "O aplikaci"
        },
        "category": {
            "title": "Vyberte Kategorii",
            "water": "Voda",
            "electricity": "Elektřina",
            "road": "Cesty",
            "garbage": "Odpad",
            "sewer": "Kanalizace",
            "streetlight": "Veřejné osvětlení",
            "park": "Park",
            "other": "Jiné",
            "description": "Popis",
            "selectCategory": "Vyberte kategorii stížnosti",
            "categoryRequired": "Kategorie je povinná",
            "categoryError": "Chyba kategorie"
        },
        "complaint": {
            "title": "Podat stížnost",
            "description": "Popis",
            "location": "Место",
            "submit": "Odeslat",
            "cancel": "Zrušit",
            "uploadImage": "Nahrát obrázek",
            "status": "Stav",
            "pending": "Nevyřešeno",
            "resolved": "Vyřešeno",
            "rejected": "Zamítnuto",
            "inProgress": "V procesu",
            "assignTo": "Přiřadit k",
            "category": "Kategorie",
            "urgency": "Naléhavost",
            "high": "Vysoká",
            "medium": "Střední",
            "low": "Nízká",
            "attachments": "Přílohy"
        },
        "roles": {
            "title": "Vyberte Svou Roli",
            "citizen": "Občan",
            "official": "Úředník",
            "admin": "Správce",
            "citizenDesc": "Hlášení problémů a stížností",
            "officialDesc": "Zpracování stížností a problémů",
            "adminDesc": "Správa systému a uživatelů",
            "selectRole": "Vyberte svou roli",
            "continue": "Pokračovat"
        },
        "bottomNav": {
            "home": "Domů",
            "complaints": "Stížnosti",
            "profile": "Profil",
            "notifications": "Oznámení"
        },
        "splash": {
            "title": "Vyavastha",
            "subtitle": "Systém správy stížností"
        },
        "home": {
            "welcome": "Vítejte",
            "recentComplaints": "Nedávné stížnosti",
            "noComplaints": "Žádné stížnosti",
            "fileComplaint": "Podat novou stížnost",
            "stats": "Statistiky",
            "resolved": "Vyřešeno",
            "pending": "Čeká se",
            "total": "Celkem",
            "viewAll": "Zobrazit vše"
        },
        "auth": {
            "login": "Přihlášení",
            "signup": "Registrace",
            "email": "E-mail",
            "password": "Heslo",
            "phone": "Telefon",
            "name": "Jméno",
            "forgotPassword": "Zapomněli jste heslo?",
            "rememberMe": "Zapamatuj si mě",
            "noAccount": "Nemáte účet?",
            "haveAccount": "Máte účet?",
            "enterOTP": "Vložte OTP",
            "sendOTP": "Odeslat OTP",
            "verifyOTP": "Ověřit OTP",
            "invalidEmail": "Neplatný e-mail",
            "invalidPhone": "Neplatné telefonní číslo",
            "passwordMismatch": "Hesla se neshodují",
            "loginSuccess": "Přihlášení úspěšné",
            "signupSuccess": "Registrace úspěšná",
            "loginError": "Chyba přihlášení",
            "signupError": "Chyba registrace"
        },
        "profile": {
            "title": "Profil",
            "name": "Jméno",
            "email": "E-mail",
            "phone": "Telefon",
            "address": "Adresa",
            "edit": "Upravit",
            "logout": "Odhlásit se"
        },
        "notifications": {
            "title": "Oznámení",
            "noNotifications": "Žádná oznámení",
            "markAsRead": "Označit jako přečtené"
        },
        "complaints": {
            "title": "Stížnosti",
            "filter": "Filtr",
            "sort": "Seřadit",
            "status": "Stav"
        },
        "languages": {
            "ar": "Arabština",
            "bn": "Bengálština",
            "cs": "Čeština",
            "de": "Němčina",
            "el": "Řečtina",
            "en": "Angličtina",
            "es": "Španělština",
            "fil": "Filipínština",
            "fr": "Francouzština",
            "gu": "Gujarátština",
            "he": "Hebrejština",
            "hi": "Hindština",
            "id": "Indonéština"
        }
    },
    "el": {
        "common": {
            "submit": "Υποβολή",
            "cancel": "Ακύρωση",
            "loading": "Φόρτωση...",
            "error": "Σφάλμα",
            "success": "Επιτυχία!",
            "warning": "Προειδοποίηση",
            "info": "Πληροφορία",
            "back": "Πίσω",
            "next": "Επόμενο",
            "done": "Ολοκληρώθηκε",
            "close": "Κλείσιμο",
            "save": "Αποθήκευση",
            "delete": "Διαγραφή",
            "edit": "Επεξεργασία",
            "logout": "Αποσύνδεση",
            "language": "Γλώσσα",
            "settings": "Ρυθμίσεις",
            "help": "Βοήθεια",
            "about": "Σχετικά"
        },
        "category": {
            "title": "Επιλέξτε Κατηγορία",
            "water": "Νερό",
            "electricity": "Ηλεκτρισμός",
            "road": "Δρόμοι",
            "garbage": "Αποχέτευση",
            "sewer": "Αποχέτευση",
            "streetlight": "Δημόσιος Φωτισμός",
            "park": "Πάρκο",
            "other": "Άλλα",
            "description": "Περιγραφή",
            "selectCategory": "Επιλέξτε κατηγορία παραπόνου",
            "categoryRequired": "Η κατηγορία είναι υποχρεωτική",
            "categoryError": "Σφάλμα κατηγορίας"
        },
        "complaint": {
            "title": "Υποβολή Παραπόνου",
            "description": "Περιγραφή",
            "location": "Τοποθεσία",
            "submit": "Υποβολή",
            "cancel": "Ακύρωση",
            "uploadImage": "Μεταφόρτωση Εικόνας",
            "status": "Κατάσταση",
            "pending": "Σε Αναμονή",
            "resolved": "Επιλύθηκε",
            "rejected": "Απορρίφθηκε",
            "inProgress": "Σε Εξέλιξη",
            "assignTo": "Ανάθεση σε",
            "category": "Κατηγορία",
            "urgency": "Επείγον",
            "high": "Υψηλή",
            "medium": "Μεσαία",
            "low": "Χαμηλή",
            "attachments": "Συνημμένα"
        },
        "roles": {
            "title": "Επιλέξτε Το Ρόλο Σας",
            "citizen": "Πολίτης",
            "official": "Υπάλληλος Κυβέρνησης",
            "admin": "Διαχειριστής",
            "citizenDesc": "Αναφορά προβλημάτων και παραπόνων",
            "officialDesc": "Επεξεργασία παραπόνων και προβλημάτων",
            "adminDesc": "Διαχείριση συστήματος και χρηστών",
            "selectRole": "Επιλέξτε το ρόλο σας",
            "continue": "Συνέχεια"
        },
        "bottomNav": {
            "home": "Αρχική",
            "complaints": "Παράπονα",
            "profile": "Προφίλ",
            "notifications": "Ειδοποιήσεις"
        },
        "splash": {
            "title": "Vyavastha",
            "subtitle": "Σύστημα Διαχείρισης Παραπόνων"
        },
        "home": {
            "welcome": "Καλώς ήρθατε",
            "recentComplaints": "Πρόσφατα Παράπονα",
            "noComplaints": "Δεν υπάρχουν Παράπονα",
            "fileComplaint": "Υποβολή Νέου Παραπόνου",
            "stats": "Στατιστικά",
            "resolved": "Επιλύθηκε",
            "pending": "Σε Αναμονή",
            "total": "Σύνολο",
            "viewAll": "Προβολή Όλων"
        },
        "auth": {
            "login": "Είσοδος",
            "signup": "Εγγραφή",
            "email": "Email",
            "password": "Κωδικός",
            "phone": "Τηλέφωνο",
            "name": "Όνομα",
            "forgotPassword": "Ξεχάσατε τον κωδικό σας;",
            "rememberMe": "Θυμήσου με",
            "noAccount": "Δεν έχεις λογαριασμό;",
            "haveAccount": "Έχετε λογαριασμό;",
            "enterOTP": "Εισαγάγετε OTP",
            "sendOTP": "Αποστολή OTP",
            "verifyOTP": "Επαλήθευση OTP",
            "invalidEmail": "Μη έγκυρη διεύθυνση ηλεκτρονικού ταχυδρομείου",
            "invalidPhone": "Μη έγκυρος αριθμός τηλεφώνου",
            "passwordMismatch": "Οι κωδικοί δεν ταιριάζουν",
            "loginSuccess": "Επιτυχής είσοδος",
            "signupSuccess": "Επιτυχής εγγραφή",
            "loginError": "Σφάλμα εισόδου",
            "signupError": "Σφάλμα εγγραφής"
        },
        "profile": {
            "title": "Προφίλ",
            "name": "Όνομα",
            "email": "Email",
            "phone": "Τηλέφωνο",
            "address": "Διεύθυνση",
            "edit": "Επεξεργασία",
            "logout": "Αποσύνδεση"
        },
        "notifications": {
            "title": "Ειδοποιήσεις",
            "noNotifications": "Δεν υπάρχουν ειδοποιήσεις",
            "markAsRead": "Επισήμανση ως διάβασμα"
        },
        "complaints": {
            "title": "Παράπονα",
            "filter": "Φίλτρο",
            "sort": "Ταξινόμηση",
            "status": "Κατάσταση"
        },
        "languages": {
            "ar": "Αραβικά",
            "bn": "Βεγγάλικα",
            "cs": "Τσεχικά",
            "de": "Γερμανικά",
            "el": "Ελληνικά",
            "en": "Αγγλικά",
            "es": "Ισπανικά",
            "fil": "Φιλιππινέζικα",
            "fr": "Γαλλικά",
            "gu": "Γκουγιαράτι",
            "he": "Εβραϊκά",
            "hi": "Χίντι",
            "id": "Ινδονησιακά"
        }
    },
    "fil": {
        "common": {
            "submit": "Ipadala",
            "cancel": "Kanselahin",
            "loading": "Naglo-load...",
            "error": "Kamalian",
            "success": "Matagumpay!",
            "warning": "Babala",
            "info": "Impormasyon",
            "back": "Bumalik",
            "next": "Susunod",
            "done": "Tapos",
            "close": "Isara",
            "save": "I-save",
            "delete": "Burahin",
            "edit": "Baguhin",
            "logout": "Mag-log out",
            "language": "Wika",
            "settings": "Mga Setting",
            "help": "Tulong",
            "about": "Tungkol sa"
        },
        "category": {
            "title": "Pumili ng Kategorya",
            "water": "Tubig",
            "electricity": "Kuryente",
            "road": "Mga Kalsada",
            "garbage": "Basura",
            "sewer": "Kanal",
            "streetlight": "Ilaw sa Publiko",
            "park": "Parke",
            "other": "Iba",
            "description": "Paglalarawan",
            "selectCategory": "Pumili ng kategorya ng reklamo",
            "categoryRequired": "Kailangan ng kategorya",
            "categoryError": "Kamalian sa kategorya"
        },
        "complaint": {
            "title": "Magpadala ng Reklamo",
            "description": "Paglalarawan",
            "location": "Lokasyon",
            "submit": "Ipadala",
            "cancel": "Kanselahin",
            "uploadImage": "Mag-upload ng Larawan",
            "status": "Status",
            "pending": "Naghihingi",
            "resolved": "Nalutas",
            "rejected": "Tinanggihan",
            "inProgress": "Sa Proseso",
            "assignTo": "Italaga sa",
            "category": "Kategorya",
            "urgency": "Kagyuan",
            "high": "Mataas",
            "medium": "Katamtaman",
            "low": "Mababa",
            "attachments": "Mga Kasama"
        },
        "roles": {
            "title": "Pumili ng Iyong Papel",
            "citizen": "Mamamayan",
            "official": "Opisyal ng Pamahalaan",
            "admin": "Administrator",
            "citizenDesc": "Iulat ang mga problema at reklamo",
            "officialDesc": "Iproseso ang mga reklamo at problema",
            "adminDesc": "Pamahalaan ang system at mga user",
            "selectRole": "Pumili ng iyong papel",
            "continue": "Magpatuloy"
        },
        "bottomNav": {
            "home": "Tahanan",
            "complaints": "Mga Reklamo",
            "profile": "Profile",
            "notifications": "Mga Abiso"
        },
        "splash": {
            "title": "Vyavastha",
            "subtitle": "Sistema ng Pamamahala ng Reklamo"
        },
        "home": {
            "welcome": "Maligayang pagdating",
            "recentComplaints": "Mga Kamakailang Reklamo",
            "noComplaints": "Walang Reklamo",
            "fileComplaint": "Magpadala ng Bagong Reklamo",
            "stats": "Mga Istatistika",
            "resolved": "Nalutas",
            "pending": "Naghihingi",
            "total": "Kabuuan",
            "viewAll": "Tingnan ang Lahat"
        },
        "auth": {
            "login": "Maglog in",
            "signup": "Mag-sign up",
            "email": "Email",
            "password": "Password",
            "phone": "Teleponong",
            "name": "Pangalan",
            "forgotPassword": "Nakalimutan ang password?",
            "rememberMe": "Alalahanin ako",
            "noAccount": "Walang account?",
            "haveAccount": "May account na?",
            "enterOTP": "Ilagay ang OTP",
            "sendOTP": "Magpadala ng OTP",
            "verifyOTP": "I-verify ang OTP",
            "invalidEmail": "Hindi wastong email",
            "invalidPhone": "Hindi wastong numero ng telepono",
            "passwordMismatch": "Hindi tumutugma ang mga password",
            "loginSuccess": "Matagumpay na pag-login",
            "signupSuccess": "Matagumpay na sign up",
            "loginError": "Error sa pag-login",
            "signupError": "Error sa sign up"
        },
        "profile": {
            "title": "Profile",
            "name": "Pangalan",
            "email": "Email",
            "phone": "Teleponong",
            "address": "Tirahan",
            "edit": "Baguhin",
            "logout": "Mag-log out"
        },
        "notifications": {
            "title": "Mga Abiso",
            "noNotifications": "Walang Mga Abiso",
            "markAsRead": "Markahan bilang Nabasa"
        },
        "complaints": {
            "title": "Mga Reklamo",
            "filter": "Salaan",
            "sort": "Pagsunod-sunod",
            "status": "Status"
        },
        "languages": {
            "ar": "Arabe",
            "bn": "Bangla",
            "cs": "Checa",
            "de": "Aleman",
            "el": "Griego",
            "en": "Ingles",
            "es": "Espanyol",
            "fil": "Filipino",
            "fr": "Pranses",
            "gu": "Gujarati",
            "he": "Hebreo",
            "hi": "Indio",
            "id": "Indonesio"
        }
    },
    "he": {
        "common": {
            "submit": "שלח",
            "cancel": "ביטול",
            "loading": "טוען...",
            "error": "שגיאה",
            "success": "הצלחה!",
            "warning": "אזהרה",
            "info": "מידע",
            "back": "חזור",
            "next": "הבא",
            "done": "בוצע",
            "close": "סגור",
            "save": "שמור",
            "delete": "מחק",
            "edit": "ערוך",
            "logout": "התנתק",
            "language": "שפה",
            "settings": "הגדרות",
            "help": "עזרה",
            "about": "אודות"
        },
        "category": {
            "title": "בחר קטגוריה",
            "water": "מים",
            "electricity": "חשמל",
            "road": "כבישים",
            "garbage": "אשפה",
            "sewer": "ביוב",
            "streetlight": "תאורת רחוב",
            "park": "פארק",
            "other": "אחר",
            "description": "תיאור",
            "selectCategory": "בחר קטגוריה של תלונה",
            "categoryRequired": "קטגוריה נדרשת",
            "categoryError": "שגיאה בקטגוריה"
        },
        "complaint": {
            "title": "הגשת תלונה",
            "description": "תיאור",
            "location": "מיקום",
            "submit": "שלח",
            "cancel": "ביטול",
            "uploadImage": "העלה תמונה",
            "status": "סטטוס",
            "pending": "ממתין",
            "resolved": "פתור",
            "rejected": "נדחה",
            "inProgress": "בתהליך",
            "assignTo": "הקצה ל",
            "category": "קטגוריה",
            "urgency": "דחיפות",
            "high": "גבוה",
            "medium": "בינוני",
            "low": "נמוך",
            "attachments": "קבצים מצורפים"
        },
        "roles": {
            "title": "בחר את התפקיד שלך",
            "citizen": "אזרח",
            "official": "פקיד ממשלתי",
            "admin": "מנהל",
            "citizenDesc": "דיווח על בעיות ותלונות",
            "officialDesc": "טיפול בתלונות ובעיות",
            "adminDesc": "ניהול מערכת ומשתמשים",
            "selectRole": "בחר את התפקיד שלך",
            "continue": "המשך"
        },
        "bottomNav": {
            "home": "בית",
            "complaints": "תלונות",
            "profile": "פרופיל",
            "notifications": "הודעות"
        },
        "splash": {
            "title": "Vyavastha",
            "subtitle": "מערכת ניהול תלונות"
        },
        "home": {
            "welcome": "ברוכים הבאים",
            "recentComplaints": "תלונות אחרונות",
            "noComplaints": "אין תלונות",
            "fileComplaint": "הגש תלונה חדשה",
            "stats": "סטטיסטיקות",
            "resolved": "פתור",
            "pending": "ממתין",
            "total": "סה\"כ",
            "viewAll": "הצג הכל"
        },
        "auth": {
            "login": "התחברות",
            "signup": "הירשם",
            "email": "אימייל",
            "password": "סיסמה",
            "phone": "טלפון",
            "name": "שם",
            "forgotPassword": "שכחת סיסמה?",
            "rememberMe": "זכור אותי",
            "noAccount": "אין לך חשבון?",
            "haveAccount": "יש לך חשבון?",
            "enterOTP": "הכנס OTP",
            "sendOTP": "שלח OTP",
            "verifyOTP": "אמת OTP",
            "invalidEmail": "אימייל לא חוקי",
            "invalidPhone": "מספר טלפון לא חוקי",
            "passwordMismatch": "הסיסמאות לא תואמות",
            "loginSuccess": "התחברות בהצלחה",
            "signupSuccess": "הרשמה בהצלחה",
            "loginError": "שגיאה בהתחברות",
            "signupError": "שגיאה בהרשמה"
        },
        "profile": {
            "title": "פרופיל",
            "name": "שם",
            "email": "אימייל",
            "phone": "טלפון",
            "address": "כתובת",
            "edit": "ערוך",
            "logout": "התנתק"
        },
        "notifications": {
            "title": "הודעות",
            "noNotifications": "אין הודעות",
            "markAsRead": "סמן כנקרא"
        },
        "complaints": {
            "title": "תלונות",
            "filter": "סנן",
            "sort": "מיין",
            "status": "סטטוס"
        },
        "languages": {
            "ar": "ערבית",
            "bn": "בנגלית",
            "cs": "צ'כית",
            "de": "גרמנית",
            "el": "יוונית",
            "en": "אנגלית",
            "es": "ספרדית",
            "fil": "פיליפינית",
            "fr": "צרפתית",
            "gu": "גוג'ראתית",
            "he": "עברית",
            "hi": "הינדית",
            "id": "אינדונזית"
        }
    },
    "id": {
        "common": {
            "submit": "Kirim",
            "cancel": "Batal",
            "loading": "Memuat...",
            "error": "Kesalahan",
            "success": "Sukses!",
            "warning": "Peringatan",
            "info": "Informasi",
            "back": "Kembali",
            "next": "Berikutnya",
            "done": "Selesai",
            "close": "Tutup",
            "save": "Simpan",
            "delete": "Hapus",
            "edit": "Edit",
            "logout": "Keluar",
            "language": "Bahasa",
            "settings": "Pengaturan",
            "help": "Bantuan",
            "about": "Tentang"
        },
        "category": {
            "title": "Pilih Kategori",
            "water": "Air",
            "electricity": "Listrik",
            "road": "Jalan",
            "garbage": "Sampah",
            "sewer": "Saluran Air",
            "streetlight": "Lampu Jalan",
            "park": "Taman",
            "other": "Lainnya",
            "description": "Deskripsi",
            "selectCategory": "Pilih kategori keluhan",
            "categoryRequired": "Kategori diperlukan",
            "categoryError": "Kesalahan kategori"
        },
        "complaint": {
            "title": "Ajukan Keluhan",
            "description": "Deskripsi",
            "location": "Lokasi",
            "submit": "Kirim",
            "cancel": "Batal",
            "uploadImage": "Unggah Gambar",
            "status": "Status",
            "pending": "Tertunda",
            "resolved": "Terselesaikan",
            "rejected": "Ditolak",
            "inProgress": "Sedang Diproses",
            "assignTo": "Tetapkan ke",
            "category": "Kategori",
            "urgency": "Urgensi",
            "high": "Tinggi",
            "medium": "Sedang",
            "low": "Rendah",
            "attachments": "Lampiran"
        },
        "roles": {
            "title": "Pilih Peran Anda",
            "citizen": "Warga",
            "official": "Pejabat Pemerintah",
            "admin": "Admin",
            "citizenDesc": "Laporkan masalah dan keluhan",
            "officialDesc": "Proses keluhan dan masalah",
            "adminDesc": "Kelola sistem dan pengguna",
            "selectRole": "Pilih peran Anda",
            "continue": "Lanjutkan"
        },
        "bottomNav": {
            "home": "Beranda",
            "complaints": "Keluhan",
            "profile": "Profil",
            "notifications": "Notifikasi"
        },
        "splash": {
            "title": "Vyavastha",
            "subtitle": "Sistem Manajemen Keluhan"
        },
        "home": {
            "welcome": "Selamat datang",
            "recentComplaints": "Keluhan Terbaru",
            "noComplaints": "Tidak ada keluhan",
            "fileComplaint": "Ajukan Keluhan Baru",
            "stats": "Statistik",
            "resolved": "Terselesaikan",
            "pending": "Tertunda",
            "total": "Total",
            "viewAll": "Lihat Semua"
        },
        "auth": {
            "login": "Masuk",
            "signup": "Daftar",
            "email": "Email",
            "password": "Kata Sandi",
            "phone": "Telepon",
            "name": "Nama",
            "forgotPassword": "Lupa Kata Sandi?",
            "rememberMe": "Ingat saya",
            "noAccount": "Tidak punya akun?",
            "haveAccount": "Sudah punya akun?",
            "enterOTP": "Masukkan OTP",
            "sendOTP": "Kirim OTP",
            "verifyOTP": "Verifikasi OTP",
            "invalidEmail": "Email tidak valid",
            "invalidPhone": "Nomor telepon tidak valid",
            "passwordMismatch": "Kata sandi tidak cocok",
            "loginSuccess": "Berhasil masuk",
            "signupSuccess": "Berhasil mendaftar",
            "loginError": "Gagal masuk",
            "signupError": "Gagal mendaftar"
        },
        "profile": {
            "title": "Profil",
            "name": "Nama",
            "email": "Email",
            "phone": "Telepon",
            "address": "Alamat",
            "edit": "Edit",
            "logout": "Keluar"
        },
        "notifications": {
            "title": "Notifikasi",
            "noNotifications": "Tidak ada notifikasi",
            "markAsRead": "Tandai sebagai dibaca"
        },
        "complaints": {
            "title": "Keluhan",
            "filter": "Filter",
            "sort": "Urutkan",
            "status": "Status"
        },
        "languages": {
            "ar": "Arab",
            "bn": "Bengali",
            "cs": "Ceko",
            "de": "Jerman",
            "el": "Yunani",
            "en": "Inggris",
            "es": "Spanyol",
            "fil": "Filipina",
            "fr": "Prancis",
            "gu": "Gujarati",
            "he": "Ibrani",
            "hi": "Hindi",
            "id": "Indonesia"
        }
    },
    "it": {
        "common": {
            "submit": "Invia",
            "cancel": "Annulla",
            "loading": "Caricamento...",
            "error": "Errore",
            "success": "Successo!",
            "warning": "Avvertenza",
            "info": "Informazione",
            "back": "Indietro",
            "next": "Avanti",
            "done": "Fatto",
            "close": "Chiudi",
            "save": "Salva",
            "delete": "Elimina",
            "edit": "Modifica",
            "logout": "Esci",
            "language": "Lingua",
            "settings": "Impostazioni",
            "help": "Aiuto",
            "about": "Informazioni"
        },
        "category": {
            "title": "Scegli una Categoria",
            "water": "Acqua",
            "electricity": "Elettricità",
            "road": "Strade",
            "garbage": "Rifiuti",
            "sewer": "Fognatura",
            "streetlight": "Illuminazione Stradale",
            "park": "Parco",
            "other": "Altro",
            "description": "Descrizione",
            "selectCategory": "Scegli la categoria del reclamo",
            "categoryRequired": "La categoria è obbligatoria",
            "categoryError": "Errore nella categoria"
        },
        "complaint": {
            "title": "Invia un Reclamo",
            "description": "Descrizione",
            "location": "Posizione",
            "submit": "Invia",
            "cancel": "Annulla",
            "uploadImage": "Carica Immagine",
            "status": "Stato",
            "pending": "In Sospeso",
            "resolved": "Risolto",
            "rejected": "Rifiutato",
            "inProgress": "In Corso",
            "assignTo": "Assegna a",
            "category": "Categoria",
            "urgency": "Urgenza",
            "high": "Alta",
            "medium": "Media",
            "low": "Bassa",
            "attachments": "Allegati"
        },
        "roles": {
            "title": "Scegli il Tuo Ruolo",
            "citizen": "Cittadino",
            "official": "Funzionario Governativo",
            "admin": "Amministratore",
            "citizenDesc": "Segnala problemi e reclami",
            "officialDesc": "Elabora reclami e problemi",
            "adminDesc": "Gestisci sistema e utenti",
            "selectRole": "Scegli il tuo ruolo",
            "continue": "Continua"
        },
        "bottomNav": {
            "home": "Home",
            "complaints": "Reclami",
            "profile": "Profilo",
            "notifications": "Notifiche"
        },
        "splash": {
            "title": "Vyavastha",
            "subtitle": "Sistema di Gestione dei Reclami"
        },
        "home": {
            "welcome": "Benvenuto",
            "recentComplaints": "Reclami Recenti",
            "noComplaints": "Nessun Reclamo",
            "fileComplaint": "Invia un Nuovo Reclamo",
            "stats": "Statistiche",
            "resolved": "Risolto",
            "pending": "In Sospeso",
            "total": "Totale",
            "viewAll": "Visualizza Tutto"
        },
        "auth": {
            "login": "Accedi",
            "signup": "Iscriviti",
            "email": "Email",
            "password": "Password",
            "phone": "Telefono",
            "name": "Nome",
            "forgotPassword": "Password Dimenticata?",
            "rememberMe": "Ricordami",
            "noAccount": "Non hai un account?",
            "haveAccount": "Hai già un account?",
            "enterOTP": "Inserisci OTP",
            "sendOTP": "Invia OTP",
            "verifyOTP": "Verifica OTP",
            "invalidEmail": "Email non valida",
            "invalidPhone": "Numero di telefono non valido",
            "passwordMismatch": "Le password non corrispondono",
            "loginSuccess": "Accesso riuscito",
            "signupSuccess": "Iscrizione riuscita",
            "loginError": "Errore di accesso",
            "signupError": "Errore di iscrizione"
        },
        "profile": {
            "title": "Profilo",
            "name": "Nome",
            "email": "Email",
            "phone": "Telefono",
            "address": "Indirizzo",
            "edit": "Modifica",
            "logout": "Esci"
        },
        "notifications": {
            "title": "Notifiche",
            "noNotifications": "Nessuna Notifica",
            "markAsRead": "Segna come Letto"
        },
        "complaints": {
            "title": "Reclami",
            "filter": "Filtro",
            "sort": "Ordina",
            "status": "Stato"
        },
        "languages": {
            "ar": "Arabo",
            "bn": "Bengalese",
            "cs": "Ceco",
            "de": "Tedesco",
            "el": "Greco",
            "en": "Inglese",
            "es": "Spagnolo",
            "fil": "Filippino",
            "fr": "Francese",
            "gu": "Gujarati",
            "he": "Ebraico",
            "hi": "Hindi",
            "id": "Indonesiano"
        }
    },
    "nl": {
        "common": {
            "submit": "Verzenden",
            "cancel": "Annuleren",
            "loading": "Laden...",
            "error": "Fout",
            "success": "Succes!",
            "warning": "Waarschuwing",
            "info": "Informatie",
            "back": "Terug",
            "next": "Volgende",
            "done": "Klaar",
            "close": "Sluiten",
            "save": "Opslaan",
            "delete": "Verwijderen",
            "edit": "Bewerken",
            "logout": "Afmelden",
            "language": "Taal",
            "settings": "Instellingen",
            "help": "Help",
            "about": "Over"
        },
        "category": {
            "title": "Kies een Categorie",
            "water": "Water",
            "electricity": "Elektriciteit",
            "road": "Wegen",
            "garbage": "Afval",
            "sewer": "Riolering",
            "streetlight": "Straatverlichting",
            "park": "Park",
            "other": "Ander",
            "description": "Beschrijving",
            "selectCategory": "Kies categorie van klacht",
            "categoryRequired": "Categorie is verplicht",
            "categoryError": "Categoriefout"
        },
        "complaint": {
            "title": "Klacht Indienen",
            "description": "Beschrijving",
            "location": "Locatie",
            "submit": "Verzenden",
            "cancel": "Annuleren",
            "uploadImage": "Afbeelding Uploaden",
            "status": "Status",
            "pending": "In Behandeling",
            "resolved": "Opgelost",
            "rejected": "Afgewezen",
            "inProgress": "In Uitvoering",
            "assignTo": "Toewijzen aan",
            "category": "Categorie",
            "urgency": "Urgentie",
            "high": "Hoog",
            "medium": "Gemiddeld",
            "low": "Laag",
            "attachments": "Bijlagen"
        },
        "roles": {
            "title": "Kies Uw Rol",
            "citizen": "Burger",
            "official": "Overheidsambtenaar",
            "admin": "Beheerder",
            "citizenDesc": "Meld problemen en klachten",
            "officialDesc": "Verwerk klachten en problemen",
            "adminDesc": "Beheer systeem en gebruikers",
            "selectRole": "Kies uw rol",
            "continue": "Doorgaan"
        },
        "bottomNav": {
            "home": "Home",
            "complaints": "Klachten",
            "profile": "Profiel",
            "notifications": "Meldingen"
        },
        "splash": {
            "title": "Vyavastha",
            "subtitle": "Klachtenbeheer Systeem"
        },
        "home": {
            "welcome": "Welkom",
            "recentComplaints": "Recente Klachten",
            "noComplaints": "Geen Klachten",
            "fileComplaint": "Dien Nieuwe Klacht In",
            "stats": "Statistieken",
            "resolved": "Opgelost",
            "pending": "In Behandeling",
            "total": "Totaal",
            "viewAll": "Alles Weergeven"
        },
        "auth": {
            "login": "Aanmelden",
            "signup": "Registreren",
            "email": "E-mail",
            "password": "Wachtwoord",
            "phone": "Telefoon",
            "name": "Naam",
            "forgotPassword": "Wachtwoord Vergeten?",
            "rememberMe": "Onthoud mij",
            "noAccount": "Geen account?",
            "haveAccount": "Al een account?",
            "enterOTP": "Voer OTP in",
            "sendOTP": "Stuur OTP",
            "verifyOTP": "Verifieer OTP",
            "invalidEmail": "Ongeldig e-mailadres",
            "invalidPhone": "Ongeldig telefoonnummer",
            "passwordMismatch": "Wachtwoorden komen niet overeen",
            "loginSuccess": "Succesvol aangemeld",
            "signupSuccess": "Succesvol geregistreerd",
            "loginError": "Aanmeldingsfout",
            "signupError": "Registratiefout"
        },
        "profile": {
            "title": "Profiel",
            "name": "Naam",
            "email": "E-mail",
            "phone": "Telefoon",
            "address": "Adres",
            "edit": "Bewerken",
            "logout": "Afmelden"
        },
        "notifications": {
            "title": "Meldingen",
            "noNotifications": "Geen Meldingen",
            "markAsRead": "Markeer als Gelezen"
        },
        "complaints": {
            "title": "Klachten",
            "filter": "Filter",
            "sort": "Sorteren",
            "status": "Status"
        },
        "languages": {
            "ar": "Arabisch",
            "bn": "Bengaals",
            "cs": "Tsjechisch",
            "de": "Duits",
            "el": "Grieks",
            "en": "Engels",
            "es": "Spaans",
            "fil": "Filipijns",
            "fr": "Frans",
            "gu": "Gujarati",
            "he": "Hebreeuws",
            "hi": "Hindi",
            "id": "Indonesisch"
        }
    },
    "pl": {
        "common": {
            "submit": "Wyślij",
            "cancel": "Anuluj",
            "loading": "Ładowanie...",
            "error": "Błąd",
            "success": "Sukces!",
            "warning": "Ostrzeżenie",
            "info": "Informacja",
            "back": "Wstecz",
            "next": "Dalej",
            "done": "Gotowe",
            "close": "Zamknij",
            "save": "Zapisz",
            "delete": "Usuń",
            "edit": "Edytuj",
            "logout": "Wyloguj się",
            "language": "Język",
            "settings": "Ustawienia",
            "help": "Pomoc",
            "about": "Informacje"
        },
        "category": {
            "title": "Wybierz Kategorię",
            "water": "Woda",
            "electricity": "Elektryczność",
            "road": "Drogi",
            "garbage": "Śmieci",
            "sewer": "Kanalizacja",
            "streetlight": "Oświetlenie Uliczne",
            "park": "Park",
            "other": "Inne",
            "description": "Opis",
            "selectCategory": "Wybierz kategorię skargi",
            "categoryRequired": "Kategoria jest wymagana",
            "categoryError": "Błąd kategorii"
        },
        "complaint": {
            "title": "Złóż Skargę",
            "description": "Opis",
            "location": "Lokalizacja",
            "submit": "Wyślij",
            "cancel": "Anuluj",
            "uploadImage": "Prześlij Obraz",
            "status": "Status",
            "pending": "Oczekująca",
            "resolved": "Rozwiązana",
            "rejected": "Odrzucona",
            "inProgress": "W Trakcie",
            "assignTo": "Przydziel do",
            "category": "Kategoria",
            "urgency": "Pilność",
            "high": "Wysoka",
            "medium": "Średnia",
            "low": "Niska",
            "attachments": "Załączniki"
        },
        "roles": {
            "title": "Wybierz Swoją Rolę",
            "citizen": "Obywatel",
            "official": "Urzędnik Rządowy",
            "admin": "Administrator",
            "citizenDesc": "Zgłaszaj problemy i skargi",
            "officialDesc": "Przetwarzaj skargi i problemy",
            "adminDesc": "Zarządzaj systemem i użytkownikami",
            "selectRole": "Wybierz swoją rolę",
            "continue": "Kontynuuj"
        },
        "bottomNav": {
            "home": "Strona Główna",
            "complaints": "Skargi",
            "profile": "Profil",
            "notifications": "Powiadomienia"
        },
        "splash": {
            "title": "Vyavastha",
            "subtitle": "System Zarządzania Skargami"
        },
        "home": {
            "welcome": "Witaj",
            "recentComplaints": "Ostatnie Skargi",
            "noComplaints": "Brak Skarg",
            "fileComplaint": "Złóż Nową Skargę",
            "stats": "Statystyki",
            "resolved": "Rozwiązana",
            "pending": "Oczekująca",
            "total": "Razem",
            "viewAll": "Pokaż Wszystkie"
        },
        "auth": {
            "login": "Zaloguj się",
            "signup": "Zarejestruj się",
            "email": "Email",
            "password": "Hasło",
            "phone": "Telefon",
            "name": "Nazwa",
            "forgotPassword": "Zapomniałeś hasła?",
            "rememberMe": "Zapamiętaj mnie",
            "noAccount": "Brak konta?",
            "haveAccount": "Masz już konto?",
            "enterOTP": "Wprowadź OTP",
            "sendOTP": "Wyślij OTP",
            "verifyOTP": "Zweryfikuj OTP",
            "invalidEmail": "Nieprawidłowy email",
            "invalidPhone": "Nieprawidłowy numer telefonu",
            "passwordMismatch": "Hasła się nie zgadzają",
            "loginSuccess": "Pomyślne zalogowanie",
            "signupSuccess": "Rejestracja pomyślna",
            "loginError": "Błąd logowania",
            "signupError": "Błąd rejestracji"
        },
        "profile": {
            "title": "Profil",
            "name": "Nazwa",
            "email": "Email",
            "phone": "Telefon",
            "address": "Adres",
            "edit": "Edytuj",
            "logout": "Wyloguj się"
        },
        "notifications": {
            "title": "Powiadomienia",
            "noNotifications": "Brak Powiadomień",
            "markAsRead": "Oznacz jako Przeczytane"
        },
        "complaints": {
            "title": "Skargi",
            "filter": "Filtr",
            "sort": "Sortuj",
            "status": "Status"
        },
        "languages": {
            "ar": "Arabski",
            "bn": "Bengalski",
            "cs": "Czeski",
            "de": "Niemiecki",
            "el": "Grecki",
            "en": "Angielski",
            "es": "Hiszpański",
            "fil": "Filipijski",
            "fr": "Francuski",
            "gu": "Gujarati",
            "he": "Hebrajski",
            "hi": "Hindi",
            "id": "Indonezyjski"
        }
    },
    "sv": {
        "common": {
            "submit": "Skicka",
            "cancel": "Avbryt",
            "loading": "Laddar...",
            "error": "Fel",
            "success": "Framgång!",
            "warning": "Varning",
            "info": "Information",
            "back": "Tillbaka",
            "next": "Nästa",
            "done": "Klart",
            "close": "Stäng",
            "save": "Spara",
            "delete": "Radera",
            "edit": "Redigera",
            "logout": "Logga ut",
            "language": "Språk",
            "settings": "Inställningar",
            "help": "Hjälp",
            "about": "Om"
        },
        "category": {
            "title": "Välj Kategori",
            "water": "Vatten",
            "electricity": "Elektricitet",
            "road": "Vägar",
            "garbage": "Sopor",
            "sewer": "Avlopp",
            "streetlight": "Gatbelysning",
            "park": "Park",
            "other": "Annat",
            "description": "Beskrivning",
            "selectCategory": "Välj klagokategori",
            "categoryRequired": "Kategori krävs",
            "categoryError": "Kategoriefel"
        },
        "complaint": {
            "title": "Lämna in Klagomål",
            "description": "Beskrivning",
            "location": "Plats",
            "submit": "Skicka",
            "cancel": "Avbryt",
            "uploadImage": "Ladda upp Bild",
            "status": "Status",
            "pending": "Väntar",
            "resolved": "Löst",
            "rejected": "Avvisad",
            "inProgress": "Pågår",
            "assignTo": "Tilldela till",
            "category": "Kategori",
            "urgency": "Brådskande",
            "high": "Hög",
            "medium": "Medel",
            "low": "Låg",
            "attachments": "Bilagor"
        },
        "roles": {
            "title": "Välj Din Roll",
            "citizen": "Medborgare",
            "official": "Regeringstjänsteman",
            "admin": "Administratör",
            "citizenDesc": "Rapportera problem och klagomål",
            "officialDesc": "Bearbeta klagomål och problem",
            "adminDesc": "Hantera system och användare",
            "selectRole": "Välj din roll",
            "continue": "Fortsätt"
        },
        "bottomNav": {
            "home": "Hem",
            "complaints": "Klagomål",
            "profile": "Profil",
            "notifications": "Meddelanden"
        },
        "splash": {
            "title": "Vyavastha",
            "subtitle": "Klagomålhanteringssystem"
        },
        "home": {
            "welcome": "Välkommen",
            "recentComplaints": "Senaste Klagomål",
            "noComplaints": "Inga Klagomål",
            "fileComplaint": "Lämna in Nytt Klagomål",
            "stats": "Statistik",
            "resolved": "Löst",
            "pending": "Väntar",
            "total": "Totalt",
            "viewAll": "Visa Allt"
        },
        "auth": {
            "login": "Logga in",
            "signup": "Registrera",
            "email": "E-post",
            "password": "Lösenord",
            "phone": "Telefon",
            "name": "Namn",
            "forgotPassword": "Glömt lösenord?",
            "rememberMe": "Kom ihåg mig",
            "noAccount": "Ingen konto?",
            "haveAccount": "Redan ett konto?",
            "enterOTP": "Ange OTP",
            "sendOTP": "Skicka OTP",
            "verifyOTP": "Verifiera OTP",
            "invalidEmail": "Ogiltig e-post",
            "invalidPhone": "Ogiltigt telefonnummer",
            "passwordMismatch": "Lösenorden matchar inte",
            "loginSuccess": "Lyckad inloggning",
            "signupSuccess": "Registrering lyckades",
            "loginError": "Inloggningsfel",
            "signupError": "Registreringsfel"
        },
        "profile": {
            "title": "Profil",
            "name": "Namn",
            "email": "E-post",
            "phone": "Telefon",
            "address": "Adress",
            "edit": "Redigera",
            "logout": "Logga ut"
        },
        "notifications": {
            "title": "Meddelanden",
            "noNotifications": "Inga Meddelanden",
            "markAsRead": "Markera som Läst"
        },
        "complaints": {
            "title": "Klagomål",
            "filter": "Filter",
            "sort": "Sortering",
            "status": "Status"
        },
        "languages": {
            "ar": "Arabiska",
            "bn": "Bengaliska",
            "cs": "Tjeckiska",
            "de": "Tyska",
            "el": "Grekiska",
            "en": "Engelska",
            "es": "Spanska",
            "fil": "Filippinska",
            "fr": "Franska",
            "gu": "Gujarati",
            "he": "Hebreiska",
            "hi": "Hindi",
            "id": "Indonesiska"
        }
    },
    "te": {
        "common": {
            "submit": "సమర్పించండి",
            "cancel": "రద్దు చేయండి",
            "loading": "లోడ్ చేస్తోంది...",
            "error": "లోపం",
            "success": "విజయం!",
            "warning": "హెచ్చరిక",
            "info": "సమాచారం",
            "back": "వెనుకకు",
            "next": "తర్వాత",
            "done": "పూర్తయింది",
            "close": "మూసివేయండి",
            "save": "సేవ్ చేయండి",
            "delete": "తొలగించండి",
            "edit": "సవరించండి",
            "logout": "లాగ్ అవుట్",
            "language": "భాష",
            "settings": "సెట్టింగ్‌లు",
            "help": "సహాయం",
            "about": "గురించి"
        },
        "category": {
            "title": "వర్గం ఎంచుకోండి",
            "water": "నీరు",
            "electricity": "విద్యుత్",
            "road": "రోడ్లు",
            "garbage": "చెత్త",
            "sewer": "సీవర్",
            "streetlight": "నీడ కాంతి",
            "park": "పార్క్",
            "other": "ఇతరులు",
            "description": "వివరణ",
            "selectCategory": "ఫిర్యాదు వర్గం ఎంచుకోండి",
            "categoryRequired": "వర్గం అవసరం",
            "categoryError": "వర్గం లోపం"
        },
        "complaint": {
            "title": "ఫిర్యాదు సమర్పించండి",
            "description": "వివరణ",
            "location": "స్థానం",
            "submit": "సమర్పించండి",
            "cancel": "రద్దు చేయండి",
            "uploadImage": "ఇమేజ్ అప్‌లోడ్ చేయండి",
            "status": "స్థితి",
            "pending": "పెండింగ్",
            "resolved": "సమర్థించారు",
            "rejected": "తిరస్కరించారు",
            "inProgress": "ప్రక్రియలో",
            "assignTo": "కు కేటాయించండి",
            "category": "వర్గం",
            "urgency": "ఆరుకుదిరిగిన",
            "high": "ఎత్తుగా",
            "medium": "మధ్యమ",
            "low": "తక్కువ",
            "attachments": "జోడింపులు"
        },
        "roles": {
            "title": "మీ పాత్ర ఎంచుకోండి",
            "citizen": "పౌరుడు",
            "official": "ప్రభుత్వ అధికారి",
            "admin": "నిర్వాహకుడు",
            "citizenDesc": "సమస్యలు మరియు ఫిర్యాదులను నివేదించండి",
            "officialDesc": "ఫిర్యాదులు మరియు సమస్యలను ప్రక్రియ చేయండి",
            "adminDesc": "సిస్టమ్ మరియు వినియోగదారులను నిర్వహించండి",
            "selectRole": "మీ పాత్ర ఎంచుకోండి",
            "continue": "కొనసాగించండి"
        },
        "bottomNav": {
            "home": "హోమ్",
            "complaints": "ఫిర్యాదులు",
            "profile": "ప్రొఫైల్",
            "notifications": "నోటిఫికేషన్‌లు"
        },
        "splash": {
            "title": "Vyavastha",
            "subtitle": "ఫిర్యాదు నిర్వహణ వ్యవస్థ"
        },
        "home": {
            "welcome": "స్వాగతం",
            "recentComplaints": "ఇటీవలి ఫిర్యాదులు",
            "noComplaints": "ఫిర్యాదులు లేవు",
            "fileComplaint": "కొత్త ఫిర్యాదు సమర్పించండి",
            "stats": "గణాంకాలు",
            "resolved": "సమర్థించారు",
            "pending": "పెండింగ్",
            "total": "మొత్తం",
            "viewAll": "అన్నీ చూడండి"
        },
        "auth": {
            "login": "ప్రవేశించండి",
            "signup": "సైన్ అప్ చేయండి",
            "email": "ఇమెయిల్",
            "password": "పాస్‌వర్డ్",
            "phone": "ఫోన్",
            "name": "పేరు",
            "forgotPassword": "పాస్‌వర్డ్ మర్చిపోయారా?",
            "rememberMe": "నన్ను గుర్తుంచుకోండి",
            "noAccount": "ఖాతా లేదా?",
            "haveAccount": "ఖాతా ఉందా?",
            "enterOTP": "OTP ఎంటర్ చేయండి",
            "sendOTP": "OTP పంపండి",
            "verifyOTP": "OTP ధృవీకరించండి",
            "invalidEmail": "చెల్లని ఇమెయిల్",
            "invalidPhone": "చెల్లని ఫోన్ నంబర్",
            "passwordMismatch": "పాస్‌వర్డ్‌లు సరిపోలలేదు",
            "loginSuccess": "విజయవంతమైన ప్రవేశం",
            "signupSuccess": "విజయవంతమైన సైన్ అప్",
            "loginError": "లాగిన్ లోపం",
            "signupError": "సైన్ అప్ లోపం"
        },
        "profile": {
            "title": "ప్రొఫైల్",
            "name": "పేరు",
            "email": "ఇమెయిల్",
            "phone": "ఫోన్",
            "address": "చిరునామా",
            "edit": "సవరించండి",
            "logout": "లాగ్ అవుట్"
        },
        "notifications": {
            "title": "నోటిఫికేషన్‌లు",
            "noNotifications": "నోటిఫికేషన్‌లు లేవు",
            "markAsRead": "చదవిన గా గుర్తించండి"
        },
        "complaints": {
            "title": "ఫిర్యాదులు",
            "filter": "ఫిల్టర్",
            "sort": "సార్టు",
            "status": "స్థితి"
        },
        "languages": {
            "ar": "అరబిక్",
            "bn": "బెంగాలీ",
            "cs": "చెక్",
            "de": "జర్మన్",
            "el": "గ్రీక్",
            "en": "ఇంగ్లీష్",
            "es": "స్పానిష్",
            "fil": "ఫిలిపినో",
            "fr": "ఫ్రెంచ్",
            "gu": "గుజరాతీ",
            "he": "హిబ్రూ",
            "hi": "హిందీ",
            "id": "ఇండోనేషియన్"
        }
    },
    "th": {
        "common": {
            "submit": "ส่ง",
            "cancel": "ยกเลิก",
            "loading": "กำลังโหลด...",
            "error": "ข้อผิดพลาด",
            "success": "สำเร็จ!",
            "warning": "คำเตือน",
            "info": "ข้อมูล",
            "back": "กลับ",
            "next": "ต่อไป",
            "done": "เสร็จ",
            "close": "ปิด",
            "save": "บันทึก",
            "delete": "ลบ",
            "edit": "แก้ไข",
            "logout": "ออกจากระบบ",
            "language": "ภาษา",
            "settings": "ตั้งค่า",
            "help": "ช่วยเหลือ",
            "about": "เกี่ยวกับ"
        },
        "category": {
            "title": "เลือกหมวดหมู่",
            "water": "น้ำ",
            "electricity": "ไฟฟ้า",
            "road": "ถนน",
            "garbage": "ขยะ",
            "sewer": "ท่อระบายน้ำ",
            "streetlight": "ไฟถนน",
            "park": "สวนสาธารณะ",
            "other": "อื่นๆ",
            "description": "คำอธิบาย",
            "selectCategory": "เลือกหมวดหมู่ของการร้องเรียน",
            "categoryRequired": "จำเป็นต้องระบุหมวดหมู่",
            "categoryError": "ข้อผิดพลาดของหมวดหมู่"
        },
        "complaint": {
            "title": "ส่งการร้องเรียน",
            "description": "คำอธิบาย",
            "location": "สถานที่",
            "submit": "ส่ง",
            "cancel": "ยกเลิก",
            "uploadImage": "อัพโหลดรูปภาพ",
            "status": "สถานะ",
            "pending": "อยู่ระหว่างดำเนิน",
            "resolved": "แก้ไขแล้ว",
            "rejected": "ปฏิเสธ",
            "inProgress": "กำลังดำเนิน",
            "assignTo": "มอบหมายให้",
            "category": "หมวดหมู่",
            "urgency": "ความเร่งด่วน",
            "high": "สูง",
            "medium": "ปานกลาง",
            "low": "ต่ำ",
            "attachments": "สิ่งที่แนบมา"
        },
        "roles": {
            "title": "เลือกบทบาทของคุณ",
            "citizen": "ประชาชน",
            "official": "เจ้าหน้าที่ภาครัฐ",
            "admin": "ผู้ดูแล",
            "citizenDesc": "รายงานปัญหาและการร้องเรียน",
            "officialDesc": "จัดการร้องเรียนและปัญหา",
            "adminDesc": "จัดการระบบและผู้ใช้",
            "selectRole": "เลือกบทบาทของคุณ",
            "continue": "ดำเนิน"
        },
        "bottomNav": {
            "home": "หน้าแรก",
            "complaints": "การร้องเรียน",
            "profile": "โปรไฟล์",
            "notifications": "การแจ้งเตือน"
        },
        "splash": {
            "title": "Vyavastha",
            "subtitle": "ระบบจัดการการร้องเรียน"
        },
        "home": {
            "welcome": "ยินดีต้อนรับ",
            "recentComplaints": "การร้องเรียนล่าสุด",
            "noComplaints": "ไม่มีการร้องเรียน",
            "fileComplaint": "ส่งการร้องเรียนใหม่",
            "stats": "สถิติ",
            "resolved": "แก้ไขแล้ว",
            "pending": "อยู่ระหว่างดำเนิน",
            "total": "รวม",
            "viewAll": "ดูทั้งหมด"
        },
        "auth": {
            "login": "เข้าสู่ระบบ",
            "signup": "สมัครสมาชิก",
            "email": "อีเมล",
            "password": "รหัสผ่าน",
            "phone": "โทรศัพท์",
            "name": "ชื่อ",
            "forgotPassword": "ลืมรหัสผ่าน?",
            "rememberMe": "จำฉันไว้",
            "noAccount": "ไม่มีบัญชี?",
            "haveAccount": "มีบัญชีแล้ว?",
            "enterOTP": "ป้อน OTP",
            "sendOTP": "ส่ง OTP",
            "verifyOTP": "ยืนยัน OTP",
            "invalidEmail": "อีเมลไม่ถูกต้อง",
            "invalidPhone": "หมายเลขโทรศัพท์ไม่ถูกต้อง",
            "passwordMismatch": "รหัสผ่านไม่ตรงกัน",
            "loginSuccess": "เข้าสู่ระบบสำเร็จ",
            "signupSuccess": "สมัครสมาชิกสำเร็จ",
            "loginError": "ข้อผิดพลาดการเข้าสู่ระบบ",
            "signupError": "ข้อผิดพลาดการสมัครสมาชิก"
        },
        "profile": {
            "title": "โปรไฟล์",
            "name": "ชื่อ",
            "email": "อีเมล",
            "phone": "โทรศัพท์",
            "address": "ที่อยู่",
            "edit": "แก้ไข",
            "logout": "ออกจากระบบ"
        },
        "notifications": {
            "title": "การแจ้งเตือน",
            "noNotifications": "ไม่มีการแจ้งเตือน",
            "markAsRead": "ทำเครื่องหมายว่าอ่านแล้ว"
        },
        "complaints": {
            "title": "การร้องเรียน",
            "filter": "ตัวกรอง",
            "sort": "จัดเรียง",
            "status": "สถานะ"
        },
        "languages": {
            "ar": "ภาษาอาหรับ",
            "bn": "ภาษาเบงกาลี",
            "cs": "ภาษาเช็ก",
            "de": "ภาษาเยอรมัน",
            "el": "ภาษากรีก",
            "en": "ภาษาอังกฤษ",
            "es": "ภาษาสเปน",
            "fil": "ภาษาฟิลิปปิโน",
            "fr": "ภาษาฝรั่งเศส",
            "gu": "ภาษากุชราติ",
            "he": "ภาษาฮิบรู",
            "hi": "ภาษาฮินดี",
            "id": "ภาษาอินโดนีเซีย"
        }
    },
    "tr": {
        "common": {
            "submit": "Gönder",
            "cancel": "İptal Et",
            "loading": "Yükleniyor...",
            "error": "Hata",
            "success": "Başarılı!",
            "warning": "Uyarı",
            "info": "Bilgi",
            "back": "Geri",
            "next": "Sonraki",
            "done": "Bitti",
            "close": "Kapat",
            "save": "Kaydet",
            "delete": "Sil",
            "edit": "Düzenle",
            "logout": "Çıkış Yap",
            "language": "Dil",
            "settings": "Ayarlar",
            "help": "Yardım",
            "about": "Hakkında"
        },
        "category": {
            "title": "Kategori Seçin",
            "water": "Su",
            "electricity": "Elektrik",
            "road": "Yollar",
            "garbage": "Çöp",
            "sewer": "Kanalizasyon",
            "streetlight": "Sokak Lambası",
            "park": "Park",
            "other": "Diğer",
            "description": "Açıklama",
            "selectCategory": "Şikayet kategorisini seçin",
            "categoryRequired": "Kategori gereklidir",
            "categoryError": "Kategori hatası"
        },
        "complaint": {
            "title": "Şikayet Gönder",
            "description": "Açıklama",
            "location": "Konum",
            "submit": "Gönder",
            "cancel": "İptal Et",
            "uploadImage": "Resim Yükle",
            "status": "Durum",
            "pending": "Beklemede",
            "resolved": "Çözüldü",
            "rejected": "Reddedildi",
            "inProgress": "İşlemde",
            "assignTo": "Ata",
            "category": "Kategori",
            "urgency": "Aciliyet",
            "high": "Yüksek",
            "medium": "Orta",
            "low": "Düşük",
            "attachments": "Ekler"
        },
        "roles": {
            "title": "Rolünüzü Seçin",
            "citizen": "Vatandaş",
            "official": "Devlet Memuru",
            "admin": "İdari",
            "citizenDesc": "Sorunları ve şikayetleri bildirin",
            "officialDesc": "Şikayetleri ve sorunları işleyin",
            "adminDesc": "Sistem ve kullanıcıları yönetin",
            "selectRole": "Rolünüzü seçin",
            "continue": "Devam Et"
        },
        "bottomNav": {
            "home": "Anasayfa",
            "complaints": "Şikayetler",
            "profile": "Profil",
            "notifications": "Bildirimler"
        },
        "splash": {
            "title": "Vyavastha",
            "subtitle": "Şikayet Yönetim Sistemi"
        },
        "home": {
            "welcome": "Hoş geldiniz",
            "recentComplaints": "Son Şikayetler",
            "noComplaints": "Şikayet Yok",
            "fileComplaint": "Yeni Şikayet Gönder",
            "stats": "İstatistikler",
            "resolved": "Çözüldü",
            "pending": "Beklemede",
            "total": "Toplam",
            "viewAll": "Tümünü Görüntüle"
        },
        "auth": {
            "login": "Giriş Yap",
            "signup": "Kaydol",
            "email": "E-posta",
            "password": "Şifre",
            "phone": "Telefon",
            "name": "Ad",
            "forgotPassword": "Şifrenizi mi unuttunuz?",
            "rememberMe": "Beni hatırla",
            "noAccount": "Hesabınız yok mu?",
            "haveAccount": "Zaten bir hesabınız var mı?",
            "enterOTP": "OTP girin",
            "sendOTP": "OTP Gönder",
            "verifyOTP": "OTP'yi Doğrula",
            "invalidEmail": "Geçersiz e-posta",
            "invalidPhone": "Geçersiz telefon numarası",
            "passwordMismatch": "Şifreler eşleşmiyor",
            "loginSuccess": "Başarıyla giriş yaptı",
            "signupSuccess": "Başarıyla kaydoldu",
            "loginError": "Giriş hatası",
            "signupError": "Kayıt hatası"
        },
        "profile": {
            "title": "Profil",
            "name": "Ad",
            "email": "E-posta",
            "phone": "Telefon",
            "address": "Adres",
            "edit": "Düzenle",
            "logout": "Çıkış Yap"
        },
        "notifications": {
            "title": "Bildirimler",
            "noNotifications": "Bildirim yok",
            "markAsRead": "Okundu Olarak İşaretle"
        },
        "complaints": {
            "title": "Şikayetler",
            "filter": "Filtre",
            "sort": "Sıralama",
            "status": "Durum"
        },
        "languages": {
            "ar": "Arapça",
            "bn": "Bengalce",
            "cs": "Çekçe",
            "de": "Almanca",
            "el": "Yunanca",
            "en": "İngilizce",
            "es": "İspanyolca",
            "fil": "Filipince",
            "fr": "Fransızca",
            "gu": "Gujarati",
            "he": "İbranice",
            "hi": "Hintçe",
            "id": "Endonezce"
        }
    },
    "uk": {
        "common": {
            "submit": "Надіслати",
            "cancel": "Скасувати",
            "loading": "Завантаження...",
            "error": "Помилка",
            "success": "Успіх!",
            "warning": "Попередження",
            "info": "Інформація",
            "back": "Назад",
            "next": "Далі",
            "done": "Готово",
            "close": "Закрити",
            "save": "Зберегти",
            "delete": "Видалити",
            "edit": "Редагувати",
            "logout": "Вихід",
            "language": "Мова",
            "settings": "Параметри",
            "help": "Допомога",
            "about": "Про нас"
        },
        "category": {
            "title": "Виберіть Категорію",
            "water": "Вода",
            "electricity": "Електроенергія",
            "road": "Дороги",
            "garbage": "Сміття",
            "sewer": "Каналізація",
            "streetlight": "Вуличне Освітлення",
            "park": "Парк",
            "other": "Інше",
            "description": "Опис",
            "selectCategory": "Виберіть категорію скарги",
            "categoryRequired": "Категорія не обов'язкова",
            "categoryError": "Помилка категорії"
        },
        "complaint": {
            "title": "Подати Скаргу",
            "description": "Опис",
            "location": "Місцевість",
            "submit": "Надіслати",
            "cancel": "Скасувати",
            "uploadImage": "Завантажити Зображення",
            "status": "Статус",
            "pending": "В Очікуванні",
            "resolved": "Вирішено",
            "rejected": "Відхилено",
            "inProgress": "В Процесі",
            "assignTo": "Призначити",
            "category": "Категорія",
            "urgency": "Невідкладність",
            "high": "Висока",
            "medium": "Середня",
            "low": "Низька",
            "attachments": "Вкладення"
        },
        "roles": {
            "title": "Виберіть Свою Роль",
            "citizen": "Громадянин",
            "official": "Державний Чиновник",
            "admin": "Адміністратор",
            "citizenDesc": "Повідомляйте про проблеми та скарги",
            "officialDesc": "Обробляйте скарги та проблеми",
            "adminDesc": "Керуйте системою та користувачами",
            "selectRole": "Виберіть свою роль",
            "continue": "Продовжити"
        },
        "bottomNav": {
            "home": "Домашня",
            "complaints": "Скарги",
            "profile": "Профіль",
            "notifications": "Повідомлення"
        },
        "splash": {
            "title": "Vyavastha",
            "subtitle": "Система Управління Скаргами"
        },
        "home": {
            "welcome": "Ласкаво просимо",
            "recentComplaints": "Недавні Скарги",
            "noComplaints": "Немає Скарг",
            "fileComplaint": "Подати Нову Скаргу",
            "stats": "Статистика",
            "resolved": "Вирішено",
            "pending": "В Очікуванні",
            "total": "Всього",
            "viewAll": "Переглянути Все"
        },
        "auth": {
            "login": "Вхід",
            "signup": "Реєстрація",
            "email": "Електронна Пошта",
            "password": "Пароль",
            "phone": "Телефон",
            "name": "Ім'я",
            "forgotPassword": "Забули Пароль?",
            "rememberMe": "Запам'ятайте мене",
            "noAccount": "Немає облікового запису?",
            "haveAccount": "Вже є облік?",
            "enterOTP": "Введіть OTP",
            "sendOTP": "Надіслати OTP",
            "verifyOTP": "Перевірити OTP",
            "invalidEmail": "Невірна електронна пошта",
            "invalidPhone": "Невалідний номер телефону",
            "passwordMismatch": "Паролі не збігаються",
            "loginSuccess": "Успішний вхід",
            "signupSuccess": "Успішна реєстрація",
            "loginError": "Помилка входу",
            "signupError": "Помилка реєстрації"
        },
        "profile": {
            "title": "Профіль",
            "name": "Ім'я",
            "email": "Електронна Пошта",
            "phone": "Телефон",
            "address": "Адреса",
            "edit": "Редагувати",
            "logout": "Вихід"
        },
        "notifications": {
            "title": "Повідомлення",
            "noNotifications": "Немає Повідомлень",
            "markAsRead": "Позначити як Прочитане"
        },
        "complaints": {
            "title": "Скарги",
            "filter": "Фільтр",
            "sort": "Сортування",
            "status": "Статус"
        },
        "languages": {
            "ar": "Арабська",
            "bn": "Бенгальська",
            "cs": "Чеська",
            "de": "Німецька",
            "el": "Грецька",
            "en": "Англійська",
            "es": "Іспанська",
            "fil": "Філіппінська",
            "fr": "Французька",
            "gu": "Гуджаратська",
            "he": "Іврит",
            "hi": "Гінді",
            "id": "Індонезійська"
        }
    },
    "vi": {
        "common": {
            "submit": "Gửi",
            "cancel": "Hủy",
            "loading": "Đang tải...",
            "error": "Lỗi",
            "success": "Thành công!",
            "warning": "Cảnh báo",
            "info": "Thông tin",
            "back": "Quay lại",
            "next": "Tiếp theo",
            "done": "Hoàn thành",
            "close": "Đóng",
            "save": "Lưu",
            "delete": "Xóa",
            "edit": "Chỉnh sửa",
            "logout": "Đăng xuất",
            "language": "Ngôn ngữ",
            "settings": "Cài đặt",
            "help": "Trợ giúp",
            "about": "Về"
        },
        "category": {
            "title": "Chọn Danh Mục",
            "water": "Nước",
            "electricity": "Điện",
            "road": "Đường",
            "garbage": "Rác",
            "sewer": "Cống",
            "streetlight": "Đèn Đường",
            "park": "Công Viên",
            "other": "Khác",
            "description": "Mô Tả",
            "selectCategory": "Chọn danh mục khiếu nại",
            "categoryRequired": "Danh mục được yêu cầu",
            "categoryError": "Lỗi danh mục"
        },
        "complaint": {
            "title": "Gửi Khiếu Nại",
            "description": "Mô Tả",
            "location": "Vị Trí",
            "submit": "Gửi",
            "cancel": "Hủy",
            "uploadImage": "Tải Lên Hình Ảnh",
            "status": "Trạng Thái",
            "pending": "Đang Chờ",
            "resolved": "Đã Giải Quyết",
            "rejected": "Bị Từ Chối",
            "inProgress": "Đang Xử Lý",
            "assignTo": "Gán Cho",
            "category": "Danh Mục",
            "urgency": "Tính Cấp Bách",
            "high": "Cao",
            "medium": "Trung Bình",
            "low": "Thấp",
            "attachments": "Tệp Đính Kèm"
        },
        "roles": {
            "title": "Chọn Vai Trò Của Bạn",
            "citizen": "Công Dân",
            "official": "Nhân Viên Chính Phủ",
            "admin": "Quản Trị Viên",
            "citizenDesc": "Báo cáo các sự cố và khiếu nại",
            "officialDesc": "Xử lý khiếu nại và sự cố",
            "adminDesc": "Quản lý hệ thống và người dùng",
            "selectRole": "Chọn vai trò của bạn",
            "continue": "Tiếp Tục"
        },
        "bottomNav": {
            "home": "Trang Chủ",
            "complaints": "Khiếu Nại",
            "profile": "Hồ Sơ",
            "notifications": "Thông Báo"
        },
        "splash": {
            "title": "Vyavastha",
            "subtitle": "Hệ Thống Quản Lý Khiếu Nại"
        },
        "home": {
            "welcome": "Chào Mừng",
            "recentComplaints": "Khiếu Nại Gần Đây",
            "noComplaints": "Không Có Khiếu Nại",
            "fileComplaint": "Gửi Khiếu Nại Mới",
            "stats": "Thống Kê",
            "resolved": "Đã Giải Quyết",
            "pending": "Đang Chờ",
            "total": "Tổng Cộng",
            "viewAll": "Xem Tất Cả"
        },
        "auth": {
            "login": "Đăng Nhập",
            "signup": "Đăng Ký",
            "email": "Email",
            "password": "Mật Khẩu",
            "phone": "Điện Thoại",
            "name": "Tên",
            "forgotPassword": "Quên Mật Khẩu?",
            "rememberMe": "Ghi Nhớ Tôi",
            "noAccount": "Không Có Tài Khoản?",
            "haveAccount": "Đã Có Tài Khoản?",
            "enterOTP": "Nhập OTP",
            "sendOTP": "Gửi OTP",
            "verifyOTP": "Xác Minh OTP",
            "invalidEmail": "Email Không Hợp Lệ",
            "invalidPhone": "Số Điện Thoại Không Hợp Lệ",
            "passwordMismatch": "Mật Khẩu Không Phù Hợp",
            "loginSuccess": "Đăng Nhập Thành Công",
            "signupSuccess": "Đăng Ký Thành Công",
            "loginError": "Lỗi Đăng Nhập",
            "signupError": "Lỗi Đăng Ký"
        },
        "profile": {
            "title": "Hồ Sơ",
            "name": "Tên",
            "email": "Email",
            "phone": "Điện Thoại",
            "address": "Địa Chỉ",
            "edit": "Chỉnh Sửa",
            "logout": "Đăng Xuất"
        },
        "notifications": {
            "title": "Thông Báo",
            "noNotifications": "Không Có Thông Báo",
            "markAsRead": "Đánh Dấu Là Đã Đọc"
        },
        "complaints": {
            "title": "Khiếu Nại",
            "filter": "Bộ Lọc",
            "sort": "Sắp Xếp",
            "status": "Trạng Thái"
        },
        "languages": {
            "ar": "Tiếng Ả Rập",
            "bn": "Tiếng Bengali",
            "cs": "Tiếng Séc",
            "de": "Tiếng Đức",
            "el": "Tiếng Hy Lạp",
            "en": "Tiếng Anh",
            "es": "Tiếng Tây Ban Nha",
            "fil": "Tiếng Philipines",
            "fr": "Tiếng Pháp",
            "gu": "Tiếng Gujarati",
            "he": "Tiếng Hebrew",
            "hi": "Tiếng Hindi",
            "id": "Tiếng Indonesia"
        }
    }
}

# Now load each language file and update with proper translations
print("\n" + "="*70)
print("UPDATING ALL 30 LANGUAGES WITH PROPER NATIVE TRANSLATIONS")
print("="*70 + "\n")

for lang_code in sorted(all_translations.keys()):
    try:
        filepath = f'{lang_code}.json'
        
        # Load existing file
        with open(filepath, 'r', encoding='utf-8-sig') as f:
            data = json.load(f)
        
        # Update with proper translations
        for section, content in all_translations[lang_code].items():
            data[section] = content
        
        # Write back
        with open(filepath, 'w', encoding='utf-8') as f:
            json.dump(data, f, ensure_ascii=False, indent=2)
        
        print(f"✓ Updated {lang_code}.json")
    except Exception as e:
        print(f"✗ Error updating {lang_code}.json: {str(e)}")

print("\n" + "="*70)
print("✅ DONE! All languages updated with proper native translations!")
print("="*70)
