import json
import os

os.chdir(os.path.dirname(__file__))

# Comprehensive translations for all languages
# For sections: roles, category, complaint, profile, notif ications, complaints, bottomNav

translations_data = {
    'es': {
        'roles': {'citizen': 'Ciudadano', 'citizenSubtitle': 'Reporta y Rastrea Problemas', 'citizenDescription': 'Envía quejas, rastrea el estado y proporciona retroalimentación', 'official': 'Funcionario Público', 'officialSubtitle': 'Resuelve Quejas', 'officialDescription': 'Ver quejas asignadas y actualizar el estado de la resolución', 'admin': 'Administrador', 'adminSubtitle': 'Gestionar Plataforma', 'adminDescription': 'Asignar quejas, gestionar departamentos, ver análisis', 'selectRoleToContinue': 'Selecciona tu rol para continuar', 'navigationInstructions': 'Usa ↑↓ o Enter para navegar • Haz clic para seleccionar'},
        'category': {'title': 'Elige Categoría', 'dirtySpot': 'Punto Sucio', 'garbageDump': 'Basural', 'garbageVehicle': 'Camión de Basura No Viene', 'burningGarbage': 'Quema de Basura en Espacio Abierto', 'sweepingNotDone': 'Barrido No Realizado', 'dustbinsNotCleaned': 'Contenedores Sin Limpiar', 'openDefecation': 'Defecación al Aire Libre', 'sewerageOverflow': 'Desbordamiento de Alcantarillado/Agua de Tormenta', 'stagnantWater': 'Agua Estancada en la Carretera', 'slumNotClean': 'Área de Tugurios Sin Limpiar', 'overgrownVegetation': 'Vegetación Excesiva en la Carretera', 'strayAnimals': 'Animales Vagabundos', 'navigateInstructions': '↑↓ o Intro para Navegar • Haz Clic para Seleccionar • Esc Atrás'},
        'complaint': {'fileComplaint': 'Presentar Queja', 'postNewComplaint': 'Presentar Nueva Queja', 'stepUploadImage': 'Imagen del Problema', 'stepSelectCategory': 'Categoría', 'stepDescribeIssue': 'Describe el Problema', 'stepSelectLocation': 'Ubicación', 'submitComplaint': 'Enviar Queja', 'myComplaints': 'Mis Quejas', 'noComplaints': 'Sin quejas aún', 'startReporting': 'Comienza a reportar problemas', 'complaintId': 'ID de Queja', 'status': 'Estado', 'date': 'Fecha', 'location': 'Ubicación', 'priority': 'Prioridad', 'high': 'Alta', 'medium': 'Media', 'low': 'Baja', 'pending': 'Pendiente', 'acknowledged': 'Reconocida', 'inProgress': 'En Progreso', 'resolved': 'Resuelta', 'rejected': 'Rechazada', 'closed': 'Cerrada'},
        'profile': {'title': 'Perfil', 'my_profile': 'Mi Perfil', 'edit_profile': 'Editar Perfil', 'settings': 'Configuración', 'points': 'Puntos', 'complaints_posted': 'Quejas Presentadas', 'resolved': 'Resuelta', 'my_complaints': 'Mis Quejas', 'help_support': 'Ayuda y Soporte', 'about_app': 'Acerca de la Aplicación', 'switch_role': 'Cambiar Rol', 'logout': 'Cerrar Sesión', 'welcome_vyavastha': 'Bienvenido a VYAVASTHA', 'login_to_track': 'Inicia sesión o regístrate para rastrear tus quejas y ganar recompensas', 'login_register': 'Iniciar Sesión / Registrarse'},
        'notifications': {'title': 'Notificaciones', 'unread': 'No Leído', 'read': 'Leído Anteriormente', 'markAllRead': 'Marcar Todo como Leído', 'noNotifications': 'Sin Notificaciones', 'complaintResolved': 'Queja Resuelta', 'complaintUpdate': 'Actualización de Queja'},
        'complaints': {'title': 'Quejas', 'myComplaints': 'Mis Quejas', 'postNew': 'Presentar Nueva Queja', 'noComplaints': 'Sin quejas aún', 'startReporting': 'Comienza a reportar problemas', 'status': 'Estado', 'pending': 'Pendiente', 'acknowledged': 'Reconocida', 'inProgress': 'En Progreso', 'underInspection': 'Bajo Inspección', 'workScheduled': 'Trabajo Programado', 'resolved': 'Resuelta', 'rejected': 'Rechazada', 'closed': 'Cerrada', 'complaintFiled': 'Queja Presentada', 'acknowledgedByOfficial': 'Reconocida por Funcionario', 'workInProgress': 'Trabajo en Progreso', 'date': 'Fecha', 'location': 'Ubicación', 'postedComplaints': 'Quejas Presentadas'},
        'bottomNav': {'home': 'Inicio', 'notifications': 'Notificaciones', 'complaints': 'Quejas', 'profile': 'Perfil'},
    },
    'fr': {
        'roles': {'citizen': 'Citoyen', 'citizenSubtitle': 'Signalez et Suivez les Problèmes', 'citizenDescription': 'Soumettez des Réclamations, Suivez le Statut, et Donnez des Retours', 'official': 'Fonctionnaire Gouvernemental', 'officialSubtitle': 'Résoudre les Réclamations', 'officialDescription': 'Consultez les Réclamations Attribuées et Mettez à Jour le Statut de Résolution', 'admin': 'Administrateur', 'adminSubtitle': 'Gérer la Plateforme', 'adminDescription': 'Attribuez les Réclamations, Gérez les Départements, Consultez les Analytiques', 'selectRoleToContinue': 'Sélectionnez Votre Rôle pour Continuer', 'navigationInstructions': 'Utilisez ↑↓ ou Entrée pour Naviguer • Cliquez pour Sélectionner'},
        'category': {'title': 'Choisir la Catégorie', 'dirtySpot': 'Endroit Sale', 'garbageDump': 'Décharge d\'Ordures', 'garbageVehicle': 'Le Camion d\'Ordures n\'Arrive Pas', 'burningGarbage': 'Incinération des Ordures en Plein Air', 'sweepingNotDone': 'Pas de Balayage', 'dustbinsNotCleaned': 'Poubelles Non Nettoyées', 'openDefecation': 'Défécation en Plein Air', 'sewerageOverflow': 'Débordement d\'Égout/Eau de Pluie', 'stagnantWater': 'Eau Stagnante sur la Route', 'slumNotClean': 'Zone de Bidonville Non Propre', 'overgrownVegetation': 'Végétation Envahissante sur la Route', 'strayAnimals': 'Animaux Errants', 'navigateInstructions': '↑↓ ou Entrée pour Naviguer • Cliquez pour Sélectionner • Esc Retour'},
        'complaint': {'fileComplaint': 'Déposer une Réclamation', 'postNewComplaint': 'Déposer une Nouvelle Réclamation', 'stepUploadImage': 'Image du Problème', 'stepSelectCategory': 'Catégorie', 'stepDescribeIssue': 'Décrivez le Problème', 'stepSelectLocation': 'Localisation', 'submitComplaint': 'Soumettre la Réclamation', 'myComplaints': 'Mes Réclamations', 'noComplaints': 'Pas encore de Réclamations', 'startReporting': 'Commencez à Signaler les Problèmes', 'complaintId': 'ID de Réclamation', 'status': 'Statut', 'date': 'Date', 'location': 'Localisation', 'priority': 'Priorité', 'high': 'Élevée', 'medium': 'Moyenne', 'low': 'Basse', 'pending': 'En Attente', 'acknowledged': 'Reconnu', 'inProgress': 'En Cours', 'resolved': 'Résolu', 'rejected': 'Rejeté', 'closed': 'Fermé'},
        'profile': {'title': 'Profil', 'my_profile': 'Mon Profil', 'edit_profile': 'Modifier le Profil', 'settings': 'Paramètres', 'points': 'Points', 'complaints_posted': 'Réclamations Soumises', 'resolved': 'Résolu', 'my_complaints': 'Mes Réclamations', 'help_support': 'Aide et Support', 'about_app': 'À Propos de l\'Application', 'switch_role': 'Changer de Rôle', 'logout': 'Déconnexion', 'welcome_vyavastha': 'Bienvenue chez VYAVASTHA', 'login_to_track': 'Connectez-vous ou Enregistrez-vous pour Suivre Vos Réclamations et Gagner des Récompenses', 'login_register': 'Connexion / Enregistrement'},
        'notifications': {'title': 'Notifications', 'unread': 'Non Lu', 'read': 'Précédemment Lu', 'markAllRead': 'Marquer Tout comme Lu', 'noNotifications': 'Pas de Notifications', 'complaintResolved': 'Réclamation Résolue', 'complaintUpdate': 'Mise à Jour de la Réclamation'},
        'complaints': {'title': 'Réclamations', 'myComplaints': 'Mes Réclamations', 'postNew': 'Déposer une Nouvelle Réclamation', 'noComplaints': 'Pas encore de Réclamations', 'startReporting': 'Commencez à Signaler les Problèmes', 'status': 'Statut', 'pending': 'En Attente', 'acknowledged': 'Reconnu', 'inProgress': 'En Cours', 'underInspection': 'Sous Inspection', 'workScheduled': 'Travail Programmé', 'resolved': 'Résolu', 'rejected': 'Rejeté', 'closed': 'Fermé', 'complaintFiled': 'Réclamation Déposée', 'acknowledgedByOfficial': 'Reconnu par le Fonctionnaire', 'workInProgress': 'Travail en Cours', 'date': 'Date', 'location': 'Localisation', 'postedComplaints': 'Réclamations Soumises'},
        'bottomNav': {'home': 'Accueil', 'notifications': 'Notifications', 'complaints': 'Réclamations', 'profile': 'Profil'},
    },
    'de': {
        'roles': {'citizen': 'Bürger', 'citizenSubtitle': 'Melden und verfolgen Sie Probleme', 'citizenDescription': 'Beschwerden einreichen, Status verfolgen und Feedback geben', 'official': 'Beamter', 'officialSubtitle': 'Beschwerden lösen', 'officialDescription': 'Zeigen Sie zugewiesene Beschwerden an und aktualisieren Sie den Lösungsstatus', 'admin': 'Administrator', 'adminSubtitle': 'Platform verwalten', 'adminDescription': 'Beschwerden zuweisen, Abteilungen verwalten, Analysen anzeigen', 'selectRoleToContinue': 'Wählen Sie Ihre Rolle aus, um fortzufahren', 'navigationInstructions': 'Verwenden Sie ↑↓ oder Enter zum Navigieren • Klicken Sie zum Auswählen'},
        'category': {'title': 'Kategorie wählen', 'dirtySpot': 'Schmutziger Ort', 'garbageDump': 'Müllkippe', 'garbageVehicle': 'Müllwagen kommt nicht', 'burningGarbage': 'Müllverbrennung auf freiem Feld', 'sweepingNotDone': 'Kehrige nicht durchgeführt', 'dustbinsNotCleaned': 'Mülleimer nicht geleert', 'openDefecation': 'Offene Fäkalienverwertung', 'sewerageOverflow': 'Abwasser-/Regenwasserüberflutung', 'stagnantWater': 'Stehendes Wasser auf der Straße', 'slumNotClean': 'Slum nicht sauber', 'overgrownVegetation': 'Überwucherung auf der Straße', 'strayAnimals': 'Streuner', 'navigateInstructions': '↑↓ oder Enter zum Navigieren • Klicken Sie zum Auswählen • Esc zurück'},
        'complaint': {'fileComplaint': 'Beschwerde einreichen', 'postNewComplaint': 'Neue Beschwerde einreichen', 'stepUploadImage': 'Foto des Problems', 'stepSelectCategory': 'Kategorie', 'stepDescribeIssue': 'Problem beschreiben', 'stepSelectLocation': 'Standort', 'submitComplaint': 'Beschwerde absenden', 'myComplaints': 'Meine Beschwerden', 'noComplaints': 'Noch keine Beschwerden', 'startReporting': 'Beginnen Sie, Probleme zu melden', 'complaintId': 'Beschwerde-ID', 'status': 'Status', 'date': 'Datum', 'location': 'Standort', 'priority': 'Priorität', 'high': 'Hoch', 'medium': 'Mittel', 'low': 'Niedrig', 'pending': 'Ausstehend', 'acknowledged': 'Bestätigt', 'inProgress': 'In Bearbeitung', 'resolved': 'Gelöst', 'rejected': 'Abgelehnt', 'closed': 'Geschlossen'},
        'profile': {'title': 'Profil', 'my_profile': 'Mein Profil', 'edit_profile': 'Profil bearbeiten', 'settings': 'Einstellungen', 'points': 'Punkte', 'complaints_posted': 'Eingereichte Beschwerden', 'resolved': 'Gelöst', 'my_complaints': 'Meine Beschwerden', 'help_support': 'Hilfe und Unterstützung', 'about_app': 'Über die App', 'switch_role': 'Rolle wechseln', 'logout': 'Abmelden', 'welcome_vyavastha': 'Willkommen bei VYAVASTHA', 'login_to_track': 'Melden Sie sich an oder registrieren Sie sich, um Ihre Beschwerden zu verfolgen und Belohnungen zu erhalten', 'login_register': 'Anmelden / Registrieren'},
        'notifications': {'title': 'Benachrichtigungen', 'unread': 'Ungelesen', 'read': 'Vorher gelesen', 'markAllRead': 'Alle als gelesen markieren', 'noNotifications': 'Keine Benachrichtigungen', 'complaintResolved': 'Beschwerde gelöst', 'complaintUpdate': 'Beschwerde-Update'},
        'complaints': {'title': 'Beschwerden', 'myComplaints': 'Meine Beschwerden', 'postNew': 'Neue Beschwerde einreichen', 'noComplaints': 'Noch keine Beschwerden', 'startReporting': 'Beginnen Sie, Probleme zu melden', 'status': 'Status', 'pending': 'Ausstehend', 'acknowledged': 'Bestätigt', 'inProgress': 'In Bearbeitung', 'underInspection': 'Unter Überprüfung', 'workScheduled': 'Arbeit geplant', 'resolved': 'Gelöst', 'rejected': 'Abgelehnt', 'closed': 'Geschlossen', 'complaintFiled': 'Beschwerde eingereicht', 'acknowledgedByOfficial': 'Von Beamten bestätigt', 'workInProgress': 'Arbeit läuft', 'date': 'Datum', 'location': 'Standort', 'postedComplaints': 'Eingereichte Beschwerden'},
        'bottomNav': {'home': 'Startseite', 'notifications': 'Benachrichtigungen', 'complaints': 'Beschwerden', 'profile': 'Profil'},
    },
    'pt': {
        'roles': {'citizen': 'Cidadão', 'citizenSubtitle': 'Denunciar e Rastrear Problemas', 'citizenDescription': 'Enviar reclamações, rastrear status e fornecer feedback', 'official': 'Funcionário Público', 'officialSubtitle': 'Resolver Reclamações', 'officialDescription': 'Ver reclamações atribuídas e atualizar status de resolução', 'admin': 'Administrador', 'adminSubtitle': 'Gerenciar Plataforma', 'adminDescription': 'Atribuir reclamações, gerenciar departamentos, visualizar análises', 'selectRoleToContinue': 'Selecione seu papel para continuar', 'navigationInstructions': 'Use ↑↓ ou Enter para navegar • Clique para selecionar'},
        'category': {'title': 'Escolha a Categoria', 'dirtySpot': 'Local Sujo', 'garbageDump': 'Depósito de Lixo', 'garbageVehicle': 'Caminhão de Lixo Não Vem', 'burningGarbage': 'Queimando Lixo em  Espaço Aberto', 'sweepingNotDone': 'Varrição Não Feita', 'dustbinsNotCleaned': 'Lixeiras Não Limpas', 'openDefecation': 'Defecação ao Ar Livre', 'sewerageOverflow': 'Transbordamento de Esgoto/Água', 'stagnantWater': 'Água Estagnada na Estrada', 'slumNotClean': 'Área de Favela Não Está Limpa', 'overgrownVegetation': 'Vegetação Excessiva na Estrada', 'strayAnimals': 'Animais Vadios', 'navigateInstructions': '↑↓ ou Enter para Navegar • Clique para Selecionar • Esc Voltar'},
        'complaint': {'fileComplaint': 'Apresentar Reclamação', 'postNewComplaint': 'Apresentar Nova Reclamação', 'stepUploadImage': 'Imagem do Problema', 'stepSelectCategory': 'Categoria', 'stepDescribeIssue': 'Descrever Problema', 'stepSelectLocation': 'Localização', 'submitComplaint': 'Enviar Reclamação', 'myComplaints': 'Minhas Reclamações', 'noComplaints': 'Sem reclamações ainda', 'startReporting': 'Comece a relatar problemas', 'complaintId': 'ID da Reclamação', 'status': 'Status', 'date': 'Data', 'location': 'Localização', 'priority': 'Prioridade', 'high': 'Alto', 'medium': 'Médio', 'low': 'Baixo', 'pending': 'Pendente', 'acknowledged': 'Reconhecido', 'inProgress': 'Em Andamento', 'resolved': 'Resolvido', 'rejected': 'Rejeitado', 'closed': 'Fechado'},
        'profile': {'title': 'Perfil', 'my_profile': 'Meu Perfil', 'edit_profile': 'Editar Perfil', 'settings': 'Configurações', 'points': 'Pontos', 'complaints_posted': 'Reclamações Enviadas', 'resolved': 'Resolvido', 'my_complaints': 'Minhas Reclamações', 'help_support': 'Ajuda e Suporte', 'about_app': 'Sobre o App', 'switch_role': 'Mudar Papel', 'logout': 'Sair', 'welcome_vyavastha': 'Bem-vindo ao VYAVASTHA', 'login_to_track': 'Faça login ou registre-se para rastrear suas reclamações e ganhar recompensas', 'login_register': 'Fazer Login / Registrar'},
        'notifications': {'title': 'Notificações', 'unread': 'Não Lido', 'read': 'Lido Anteriormente', 'markAllRead': 'Marcar Todos como Lido', 'noNotifications': 'Sem Notificações', 'complaintResolved': 'Reclamação Resolvida', 'complaintUpdate': 'Atualização de Reclamação'},
        'complaints': {'title': 'Reclamações', 'myComplaints': 'Minhas Reclamações', 'postNew': 'Apresentar Nova Reclamação', 'noComplaints': 'Sem reclamações ainda', 'startReporting': 'Comece a relatar problemas', 'status': 'Status', 'pending': 'Pendente', 'acknowledged': 'Reconhecido', 'inProgress': 'Em Andamento', 'underInspection': 'Sob Inspeção', 'workScheduled': 'Trabalho Agendado', 'resolved': 'Resolvido', 'rejected': 'Rejeitado', 'closed': 'Fechado', 'complaintFiled': 'Reclamação Apresentada', 'acknowledgedByOfficial': 'Reconhecido por Oficial', 'workInProgress': 'Trabalho em Andamento', 'date': 'Data', 'location': 'Localização', 'postedComplaints': 'Reclamações Enviadas'},
        'bottomNav': {'home': 'Início', 'notifications': 'Notificações', 'complaints': 'Reclamações', 'profile': 'Perfil'},
    }
}

# Update files
print(f"Updating {len(translations_data)} language files with proper translations...\n")

for lang_code, translations in translations_data.items():
    lang_file = f"{lang_code}.json"
    try:
        with open(lang_file, 'r', encoding='utf-8') as f:
            lang_data = json.load(f)
        
        # Update sections
        for section, content in translations.items():
            lang_data[section] = content
        
        # Write back
        with open(lang_file, 'w', encoding='utf-8') as f:
            json.dump(lang_data, f, ensure_ascii=False, indent=2)
        
        print(f"✓ {lang_code}.json: Updated with proper translations")
    except Exception as e:
        print(f"✗ Error with {lang_file}: {e}")

print(f"\nAll language files have been updated!")
