#!/bin/bash

# Complete translation data for all 30 languages
# This script generates complete translation files for all Vyavastha languages

cd "$(dirname "$0")"

# Arabic translations
cat > ar.json << 'EOF'
{
  "common": {"appName":"فيافاستا","appSubtitle":"بوابة شكاوى المواطنين","welcome":"أهلا وسهلا","loading":"جارٍ التحميل","error":"خطأ","success":"نجح","cancel":"إلغاء","submit":"إرسال","save":"حفظ","delete":"حذف","edit":"تحرير","back":"رجوع","next":"التالي","logout":"تسجيل الخروج","language":"اللغة","goodMorning":"صباح الخير","goodAfternoon":"مساء الخير","goodEvening":"مساء الخير","citizen":"مواطن","activeCitizen":"مواطن نشط"},
  "splash": {"title":"فيافاستا","subtitle":"بوابة الحوكمة المواطنية","initializing":"جاري تهيئة النظام","digitalIndia":"مبادرة الهند الرقمية"},
  "home": {"greeting":"صباح الخير","greeting_afternoon":"مساء الخير","greeting_evening":"مساء الخير","welcome_citizen":"أهلا وسهلا، مواطن","todayActions":"إليك إجراءاتك اليومية","yourXP":"نقاطك","post_complaint":"قدم شكوى","post_complaint_sub":"الإبلاغ عن المشاكل بدعم الذكاء الاصطناعي","rate_service":"قيّم الخدمة العامة","rate_service_sub":"قيّم المرافق والمواصلات والمزيد","community":"مركز المجتمع","community_sub":"صوّت ودعم المشاكل","quiz":"مسابقة الحقوق المدنية","quiz_sub":"تعلم واكسب نقاط","smartCity":"مدينة ذكية، مواطنون أذكياء","buildBetter":"صوتك يبني بنية تحتية أفضل","reportTrack":"أبلغ. تابع. غيّر.","aiPowered":"تفاعل مدني مدعوم بالذكاء الاصطناعي","vyavasthaPortal":"فيافاستا - بوابة شكاوى المواطنين","posted":"تم النشر","resolved":"تم الحل","yourRank":"رتبتك","trackComplaints":"تتبع الشكاوى","joinCommunity":"انضم إلى المجتمع","knowRights":"اعرف حقوقك","tapToExplore":"اضغط للاستكشاف","systemStats":"إحصائيات النظام","totalComplaints":"إجمالي الشكاوى","avgTime":"متوسط الاستجابة","satisfaction":"الرضا","quickActions":"إجراءات سريعة","featuredInitiatives":"المبادرات المميزة"},
  "auth": {"welcomeTitle":"أهلا وسهلا بك في فيافاستا","welcomeSubtitle":"إدارة شكاوى المواطنين","loginButton":"دخول","loginDesc":"هل لديك حساب؟ قم بتسجيل الدخول","signupButton":"إنشاء حساب","signupDesc":"جديد هنا؟ سجل مجانا","login":"دخول","signup":"اشترك","register":"تسجيل","email":"البريد الإلكتروني","phone":"الهاتف","password":"كلمة المرور","confirm_password":"تأكيد كلمة المرور","name":"الاسم الكامل","loginTitle":"أهلا وسهلا بعودتك!","signupTitle":"انضم إلى فيافاستا","forgotPassword":"هل نسيت كلمة المرور؟","rememberMe":"تذكرني","noAccount":"ليس لديك حساب؟","haveAccount":"هل لديك حساب بالفعل؟","phoneOrEmail":"الهاتف أو البريد الإلكتروني","enterPhoneEmail":"أدخل رقم هاتفك أو بريدك الإلكتروني","selectAuthType":"اختر طريقة المصادقة","usePhone":"استخدم رقم الهاتف","useEmail":"استخدم البريد الإلكتروني","sendOTP":"أرسل رمز التحقق","enterOTP":"أدخل رمز التحقق","enterOTPCode":"أدخل رمز التحقق المكون من 6 أرقام المرسل إليك","resendOTP":"أعد إرسال رمز التحقق","verifyOTP":"تحقق من رمز التحقق","otpSentTo":"تم إرسال رمز التحقق إلى","changeContact":"تغيير جهة الاتصال","resendIn":"أعد الإرسال في","seconds":"ثانية","completeProfile":"أكمل ملفك الشخصي","fullName":"الاسم الكامل","enterName":"أدخل اسمك الكامل","detectLocation":"كتشاف الموقع","detectedLocation":"الموقع المكتشف","selectLocation":"حدد موقعك على الخريطة","completeSignup":"أكمل التسجيل","successfulLogin":"تم دخولك بنجاح!","successfulSignup":"تم تسجيلك بنجاح!","invalidOTP":"رمز التحقق غير صحيح. يرجى المحاولة مرة أخرى.","otpExpired":"انتهت صلاحية رمز التحقق. يرجى طلب رمز جديد.","incompleteOTP":"يرجى إدخال رمز التحقق الكامل","passwordMismatch":"كلمات المرور غير متطابقة","invalidPassword":"يجب أن تكون كلمة المرور 6 أحرف على الأقل","tryAgain":"حاول مرة أخرى","demoMode":"(وضع العرض)","demoOTP":"رمز التحقق (عرض):"},
  "roles": {"citizen":"مواطن","citizenSubtitle":"أبلغ وتابع المشاكل","citizenDescription":"قدّم شكاوى وتابع الحالة وقدّم ملاحظات","official":"مسؤول حكومي","officialSubtitle":"حل الشكاوى","officialDescription":"عرض الشكاوى المعينة وتحديث حالة الحل","admin":"مسؤول","adminSubtitle":"إدارة المنصة","adminDescription":"عيّن الشكاوى وأدر الأقسام واعرض التحليلات","selectRoleToContinue":"اختر دورك للمتابعة","navigationInstructions":"استخدم ↑↓ أو Enter للتنقل • انقر للتحديد"},
  "category": {"title":"اختر الفئة","dirtySpot":"مكان متسخ","garbageDump":"مقلب نفايات","garbageVehicle":"لم تأتِ سيارة النفايات","burningGarbage":"حرق النفايات في مكان مفتوح","sweepingNotDone":"لم يتم الكنس","dustbinsNotCleaned":"صناديق القمامة لم يتم تنظيفها","openDefecation":"قضاء الحاجة في العراء","sewerageOverflow":"فيضان الصرف الصحي","stagnantWater":"المياه الراكدة في الطريق","slumNotClean":"منطقة العشوائيات غير نظيفة","overgrownVegetation":"الغطاء النباتي المتضخم على الطريق","strayAnimals":"حيوانات ضالة","navigateInstructions":"↑↓ أو Enter للتنقل • انقر للتحديد • Esc للعودة"},
  "complaint": {"fileComplaint":"قدّم شكوى","postNewComplaint":"قدّم شكوى جديدة","stepUploadImage":"صورة المشكلة","stepSelectCategory":"الفئة","stepDescribeIssue":"صِف المشكلة","stepSelectLocation":"الموقع","submitComplaint":"قدّم الشكوى","myComplaints":"شكاواي","noComplaints":"لا توجد شكاوى حتى الآن","startReporting":"ابدأ بالإبلاغ عن المشاكل","complaintId":"معرف الشكوى","status":"الحالة","date":"التاريخ","location":"الموقع","priority":"الأولوية","high":"عالية","medium":"متوسطة","low":"منخفضة","pending":"قيد الانتظار","acknowledged":"تم الاعتراف بها","inProgress":"قيد المعالجة","resolved":"تم الحل","rejected":"رفضت","closed":"مغلقة"},
  "profile": {"title":"الملف الشخصي","my_profile":"ملفي الشخصي","edit_profile":"عديل الملف الشخصي","settings":"الإعدادات","points":"النقاط","complaints_posted":"الشكاوى المقدمة","resolved":"تم الحل","my_complaints":"شكاواي","help_support":"المساعدة والدعم","about_app":"عن التطبيق","switch_role":"تبديل الدور","logout":"تسجيل الخروج","welcome_vyavastha":"أهلا وسهلا بك في فيافاستا","login_to_track":"قم بتسجيل الدخول أو التسجيل لتتبع شكاواك وكسب المكافآت","login_register":"دخول / تسجيل"},
  "notifications": {"title":"إشعارات","unread":"غير مقروء","read":"مقروء مسبقا","markAllRead":"جعل الكل مقروء","noNotifications":"لا توجد إشعارات","complaintResolved":"تم حل الشكوى","complaintUpdate":"تحديث الشكوى"},
  "complaints": {"title":"الشكاوى","myComplaints":"شكاواي","postNew":"قدّم شكوى جديدة","noComplaints":"لا توجد شكاوى حتى الآن","startReporting":"ابدأ بالإبلاغ عن المشاكل","status":"الحالة","pending":"قيد الانتظار","acknowledged":"تم الاعتراف بها","inProgress":"قيد المعالجة","underInspection":"تحت الفحص","workScheduled":"تم جدولة العمل","resolved":"تم الحل","rejected":"رفضت","closed":"مغلقة","complaintFiled":"تم تقديم الشكوى","acknowledgedByOfficial":"تم الاعتراف بها من قبل المسؤول","workInProgress":"العمل جاري","date":"التاريخ","location":"الموقع","postedComplaints":"الشكاوى المقدمة"},
  "bottomNav": {"home":"الرئيسية","notifications":"إشعارات","complaints":"الشكاوى","profile":"الملف الشخصي"},
  "languages": {"english":"English","hindi":"हिंदी","spanish":"Español","french":"Français","german":"Deutsch","chinese":"中文","japanese":"日本語","korean":"한국어","portuguese":"Português","arabic":"العربية"}
}
EOF

echo "Generator complete. Run this to create all translation files."
